#!/usr/bin/env python3
"""Round 21 · Final: generate an NLP prerequisite project package."""

from __future__ import annotations

import csv
import json
import shutil
import subprocess
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[3]
LAB = Path.home() / "cli-lab" / "round21" / "final_auto" / "nlp_prereq_lab"

README = """# Round 21 NLP prerequisite lab

Generated by the Web UI final exercise.

Files:

- `tokenizer.py`: manual tokenizer with `<PAD>` and `<UNK>`.
- `dataset.py`: text dataset, encode, padding, and DataLoader shape.
- `embedding_model.py`: embedding + masked mean pooling classifier shape.
- `traditional_baseline.py`: TF-IDF + linear classifier shape.
- `data/sentiment_samples.csv`: small labeled text dataset.
- `pipeline_contract.json`: required workflow and concepts.
- `stdlib_smoke.py`: dependency-free end-to-end smoke check.
- `final_static_check.py`: AST and contract verification.

The PyTorch / scikit-learn files are real code shapes. The Web UI smoke check uses only Python standard library so this Round does not require installing large dependencies.
"""

TOKENIZER = '''"""Manual tokenizer used by the Round 21 final package."""

from __future__ import annotations

import re


class SimpleTokenizer:
    def __init__(self) -> None:
        self.pad_token = "<PAD>"
        self.unk_token = "<UNK>"
        self.token_to_id: dict[str, int] = {}
        self.id_to_token: dict[int, str] = {}
        self.add_token(self.pad_token)
        self.add_token(self.unk_token)

    def add_token(self, token: str) -> int:
        if token not in self.token_to_id:
            index = len(self.token_to_id)
            self.token_to_id[token] = index
            self.id_to_token[index] = token
        return self.token_to_id[token]

    def tokenize(self, text: str) -> list[str]:
        return re.findall(r"[a-z0-9']+", text.lower())

    def build_vocab(self, texts: list[str]) -> None:
        for text in texts:
            for token in self.tokenize(text):
                self.add_token(token)

    def encode(self, text: str) -> list[int]:
        unknown_id = self.token_to_id[self.unk_token]
        return [self.token_to_id.get(token, unknown_id) for token in self.tokenize(text)]

    def decode(self, ids: list[int]) -> str:
        return " ".join(self.id_to_token.get(index, self.unk_token) for index in ids)
'''

DATASET = '''"""Text dataset and padding shape for the Round 21 final package."""

from __future__ import annotations

import csv
from pathlib import Path

import torch
from torch.utils.data import Dataset, DataLoader

from tokenizer import SimpleTokenizer


class SentimentDataset(Dataset):
    def __init__(self, path: Path, tokenizer: SimpleTokenizer, max_len: int = 8) -> None:
        with path.open("r", encoding="utf-8", newline="") as f:
            rows = list(csv.DictReader(f))
        tokenizer.build_vocab([row["text"] for row in rows])
        pad_id = tokenizer.token_to_id[tokenizer.pad_token]
        self.rows = []
        for row in rows:
            ids = tokenizer.encode(row["text"])[:max_len]
            padded = ids + [pad_id] * (max_len - len(ids))
            self.rows.append((torch.tensor(padded, dtype=torch.long), torch.tensor(int(row["label"]), dtype=torch.long)))

    def __len__(self) -> int:
        return len(self.rows)

    def __getitem__(self, index: int):
        return self.rows[index]


def build_loader(path: Path, batch_size: int = 4) -> DataLoader:
    tokenizer = SimpleTokenizer()
    return DataLoader(SentimentDataset(path, tokenizer), batch_size=batch_size, shuffle=True)
'''

EMBEDDING_MODEL = '''"""Embedding classifier shape for the Round 21 final package."""

from __future__ import annotations

import torch
from torch import nn


class EmbeddingTextClassifier(nn.Module):
    def __init__(self, vocab_size: int, embedding_dim: int = 16, num_classes: int = 2, padding_idx: int = 0) -> None:
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, embedding_dim, padding_idx=padding_idx)
        self.classifier = nn.Linear(embedding_dim, num_classes)

    def forward(self, token_ids: torch.Tensor) -> torch.Tensor:
        embedded = self.embedding(token_ids)
        mask = (token_ids != 0).unsqueeze(-1)
        pooled = (embedded * mask).sum(dim=1) / mask.sum(dim=1).clamp(min=1)
        return self.classifier(pooled)
'''

TRADITIONAL_BASELINE = '''"""Traditional text classification baseline shape."""

from __future__ import annotations

import csv
from pathlib import Path

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report


def train_baseline(path: Path) -> None:
    with path.open("r", encoding="utf-8", newline="") as f:
        rows = list(csv.DictReader(f))
    texts = [row["text"] for row in rows]
    labels = [int(row["label"]) for row in rows]
    vectorizer = TfidfVectorizer()
    X = vectorizer.fit_transform(texts)
    model = LogisticRegression()
    model.fit(X, labels)
    pred = model.predict(X)
    print(classification_report(labels, pred, target_names=["negative", "positive"]))
'''

STDLIB_SMOKE = '''#!/usr/bin/env python3
"""Dependency-free end-to-end smoke check for the Round 21 final package."""

from __future__ import annotations

import csv
import json
import re
from collections import Counter
from pathlib import Path


base = Path(__file__).resolve().parent
data_path = base / "data" / "sentiment_samples.csv"
with data_path.open("r", encoding="utf-8", newline="") as f:
    rows = list(csv.DictReader(f))


def tokenize(text: str) -> list[str]:
    return re.findall(r"[a-z0-9']+", text.lower())


vocab = {"<PAD>": 0, "<UNK>": 1}
for row in rows:
    for token in tokenize(row["text"]):
        if token not in vocab:
            vocab[token] = len(vocab)


def encode(text: str, max_len: int = 6) -> list[int]:
    ids = [vocab.get(token, vocab["<UNK>"]) for token in tokenize(text)][:max_len]
    return ids + [vocab["<PAD>"]] * (max_len - len(ids))


def fake_vector(token_id: int, dim: int = 4) -> list[float]:
    if token_id == vocab["<PAD>"]:
        return [0.0] * dim
    return [round((((token_id + 3) * (axis + 1)) % 13 - 6) * 0.1, 3) for axis in range(dim)]


def mean_pool(ids: list[int]) -> list[float]:
    vectors = [fake_vector(token_id) for token_id in ids if token_id != vocab["<PAD>"]]
    scale = len(vectors) ** -1 if vectors else 1.0
    return [round(sum(vector[axis] for vector in vectors) * scale, 3) for axis in range(4)]


class_counts = {0: Counter(), 1: Counter()}
for row in rows:
    class_counts[int(row["label"])].update(tokenize(row["text"]))


def baseline_predict(text: str) -> str:
    tokens = tokenize(text)
    positive = sum(class_counts[1][token] for token in tokens)
    negative = sum(class_counts[0][token] for token in tokens)
    return "positive" if positive >= negative else "negative"


probe = "great excellent movie"
encoded = encode(probe)
summary = {
    "rows": len(rows),
    "vocab_size": len(vocab),
    "pad_id": vocab["<PAD>"],
    "unk_id": vocab["<UNK>"],
    "probe": probe,
    "encoded": encoded,
    "pooled_vector": mean_pool(encoded),
    "baseline_prediction": baseline_predict(probe),
    "workflow": ["tokenize", "vocab", "encode", "pad", "embedding intuition", "traditional baseline"],
    "required_concepts": ["tokenization", "vocabulary", "embedding", "TF-IDF", "BPE", "WordPiece"],
}
(base / "round21_final_summary.json").write_text(json.dumps(summary, ensure_ascii=False, indent=2) + "\\n", encoding="utf-8")
print(json.dumps(summary, ensure_ascii=False, sort_keys=True))
'''

FINAL_CHECK = '''#!/usr/bin/env python3
"""Final static checks for the Round 21 NLP prerequisite package."""

from __future__ import annotations

import ast
import csv
import json
import subprocess
import sys
from pathlib import Path


base = Path(__file__).resolve().parent
sources = {
    name: (base / name).read_text(encoding="utf-8")
    for name in ("tokenizer.py", "dataset.py", "embedding_model.py", "traditional_baseline.py")
}
for source in sources.values():
    ast.parse(source)

with (base / "data" / "sentiment_samples.csv").open("r", encoding="utf-8", newline="") as f:
    rows = list(csv.DictReader(f))

proc = subprocess.run([sys.executable, "stdlib_smoke.py"], cwd=base, capture_output=True, text=True, check=False)
summary = {}
if proc.returncode == 0:
    summary = json.loads((base / "round21_final_summary.json").read_text(encoding="utf-8"))

contract = json.loads((base / "pipeline_contract.json").read_text(encoding="utf-8"))
checks = {
    "tokenizer_contract": all(text in sources["tokenizer.py"] for text in ("SimpleTokenizer", "<PAD>", "<UNK>", "build_vocab", "encode", "decode")),
    "dataset_contract": all(text in sources["dataset.py"] for text in ("SentimentDataset", "Dataset", "DataLoader", "padded")),
    "embedding_model_contract": all(text in sources["embedding_model.py"] for text in ("nn.Embedding", "padding_idx", "nn.Linear", "mask", "clamp(min=1)")),
    "traditional_baseline_contract": all(text in sources["traditional_baseline.py"] for text in ("TfidfVectorizer", "LogisticRegression", "classification_report")),
    "data_rows": len(rows) == 8 and set(rows[0]) == {"id", "text", "label"},
    "smoke_runs": proc.returncode == 0 and summary.get("baseline_prediction") == "positive",
    "contract": contract.get("workflow") == ["tokenization", "vocabulary", "encoding", "embedding_classifier", "traditional_baseline"],
}
report = {"ok": all(checks.values()), "checks": checks, "summary": summary, "stderr": proc.stderr.strip()}
(base / "final_static_check_report.json").write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\\n", encoding="utf-8")
print(json.dumps(report, ensure_ascii=False, sort_keys=True))
raise SystemExit(0 if report["ok"] else 1)
'''

CONTRACT = {
    "project": "round21_nlp_prereq_lab",
    "inputs": ["data/sentiment_samples.csv"],
    "workflow": ["tokenization", "vocabulary", "encoding", "embedding_classifier", "traditional_baseline"],
    "concepts": ["SimpleTokenizer", "special tokens", "padding", "nn.Embedding", "masked pooling", "TF-IDF", "BPE", "WordPiece"],
    "outputs": ["round21_final_summary.json", "final_static_check_report.json"],
}

DATA_ROWS = [
    {"id": 1, "text": "great movie love it", "label": "1"},
    {"id": 2, "text": "terrible waste of time", "label": "0"},
    {"id": 3, "text": "amazing excellent film", "label": "1"},
    {"id": 4, "text": "boring bad movie", "label": "0"},
    {"id": 5, "text": "really enjoyed this movie", "label": "1"},
    {"id": 6, "text": "hated every boring minute", "label": "0"},
    {"id": 7, "text": "brilliant and great", "label": "1"},
    {"id": 8, "text": "awful terrible trash", "label": "0"},
]


def mark(task_id: str) -> None:
    subprocess.run(["bash", str(REPO_ROOT / "mark_done.sh"), task_id], cwd=REPO_ROOT, check=True)


def reset_lab() -> None:
    if LAB.exists():
        shutil.rmtree(LAB)
    (LAB / "data").mkdir(parents=True)


def write_csv(path: Path) -> None:
    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=["id", "text", "label"])
        writer.writeheader()
        writer.writerows(DATA_ROWS)


def main() -> None:
    reset_lab()
    (LAB / "README.md").write_text(README, encoding="utf-8")
    (LAB / "tokenizer.py").write_text(TOKENIZER, encoding="utf-8")
    (LAB / "dataset.py").write_text(DATASET, encoding="utf-8")
    (LAB / "embedding_model.py").write_text(EMBEDDING_MODEL, encoding="utf-8")
    (LAB / "traditional_baseline.py").write_text(TRADITIONAL_BASELINE, encoding="utf-8")
    (LAB / "pipeline_contract.json").write_text(json.dumps(CONTRACT, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    write_csv(LAB / "data" / "sentiment_samples.csv")
    smoke = LAB / "stdlib_smoke.py"
    smoke.write_text(STDLIB_SMOKE, encoding="utf-8")
    smoke.chmod(0o755)
    check = LAB / "final_static_check.py"
    check.write_text(FINAL_CHECK, encoding="utf-8")
    check.chmod(0o755)
    proc = subprocess.run(["python3", str(check)], cwd=LAB, capture_output=True, text=True, check=False)
    if proc.returncode != 0:
        raise RuntimeError(proc.stderr or proc.stdout)
    print("Round 21 Final NLP prerequisite project package")
    print("sandbox:", LAB)
    print("summary:", LAB / "round21_final_summary.json")
    print("report:", LAB / "final_static_check_report.json")
    mark("r21-fin-comp")


if __name__ == "__main__":
    main()
