#!/usr/bin/env python3
"""Round 15 · Week 3: generate docs examples and an OpenAPI preview."""

from __future__ import annotations

import json
import shutil
import subprocess
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[3]
LAB = Path.home() / "cli-lab" / "round15" / "week3_auto" / "docs_examples"

SCHEMAS_PY = '''"""Pydantic schemas with example data for Round 15 Week 3."""

from pydantic import BaseModel, Field


class RunRequest(BaseModel):
    input_file: str = Field(..., description="Input file path", examples=["input/demo.txt"])
    format: str = Field("txt", description="Input file format", examples=["txt"])
    dedup: bool = Field(False, description="Whether to remove duplicates")

    model_config = {
        "json_schema_extra": {
            "example": {"input_file": "input/demo.txt", "format": "txt", "dedup": True}
        }
    }


class RunResponse(BaseModel):
    run_id: int = Field(..., examples=[1001])
    status: str = Field(..., examples=["completed"])
    input_file: str
    processed_count: int | None = None
    message: str | None = None
'''

MAIN_PY = '''"""FastAPI docs example route generated by Round 15 Week 3."""

from fastapi import FastAPI
from app.schemas import RunRequest, RunResponse

app = FastAPI(title="AI Prep Tool API", version="0.1.0")


@app.post(
    "/run",
    response_model=RunResponse,
    tags=["jobs"],
    summary="Submit one data-processing run",
)
def trigger_run(req: RunRequest) -> RunResponse:
    """Submit one file-processing request and return a structured result."""
    return RunResponse(run_id=1001, status="completed", input_file=req.input_file, processed_count=3)
'''

DOCS_CHECK = '''#!/usr/bin/env python3
"""Check documentation-oriented fields for generated FastAPI files."""

import json
from pathlib import Path

base = Path(__file__).resolve().parent
schemas = (base / "app" / "schemas.py").read_text(encoding="utf-8")
main = (base / "app" / "main.py").read_text(encoding="utf-8")
examples = json.loads((base / "docs_examples.json").read_text(encoding="utf-8"))
openapi = json.loads((base / "openapi_preview.json").read_text(encoding="utf-8"))
checks = {
    "schema_extra_example": "json_schema_extra" in schemas and "input/demo.txt" in schemas,
    "route_summary": 'summary="Submit one data-processing run"' in main,
    "route_tags": 'tags=["jobs"]' in main,
    "response_model": "response_model=RunResponse" in main,
    "examples_json": {"request", "response"}.issubset(examples),
    "openapi_path": "/run" in openapi.get("paths", {}),
}
report = {"ok": all(checks.values()), "checks": checks}
(base / "docs_quality_report.json").write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\\n", encoding="utf-8")
print(json.dumps(report, ensure_ascii=False, sort_keys=True))
raise SystemExit(0 if report["ok"] else 1)
'''


def mark(task_id: str) -> None:
    subprocess.run(["bash", str(REPO_ROOT / "mark_done.sh"), task_id], cwd=REPO_ROOT, check=True)


def reset_lab() -> None:
    if LAB.exists():
        shutil.rmtree(LAB)
    (LAB / "app").mkdir(parents=True)


def main() -> None:
    reset_lab()
    (LAB / "app" / "__init__.py").write_text("", encoding="utf-8")
    (LAB / "app" / "schemas.py").write_text(SCHEMAS_PY, encoding="utf-8")
    (LAB / "app" / "main.py").write_text(MAIN_PY, encoding="utf-8")
    examples = {
        "request": {"input_file": "input/demo.txt", "format": "txt", "dedup": True},
        "response": {"run_id": 1001, "status": "completed", "input_file": "input/demo.txt", "processed_count": 3},
    }
    (LAB / "docs_examples.json").write_text(json.dumps(examples, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    (LAB / "openapi_preview.json").write_text(
        json.dumps(
            {
                "openapi": "3.1.0-preview",
                "info": {"title": "AI Prep Tool API", "version": "0.1.0"},
                "paths": {
                    "/run": {
                        "post": {
                            "summary": "Submit one data-processing run",
                            "tags": ["jobs"],
                            "requestBody": {"example": examples["request"]},
                            "responses": {"200": {"description": "Structured run response", "example": examples["response"]}},
                        }
                    }
                },
            },
            ensure_ascii=False,
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    check = LAB / "docs_quality_check.py"
    check.write_text(DOCS_CHECK, encoding="utf-8")
    check.chmod(0o755)
    proc = subprocess.run(["python3", str(check)], cwd=LAB, capture_output=True, text=True, check=False)
    if proc.returncode != 0:
        raise RuntimeError(proc.stderr or proc.stdout)
    print("Round 15 Week 3 文档示例与 OpenAPI 预览")
    print("sandbox:", LAB)
    print("example_count:", 2)
    print("report:", LAB / "docs_quality_report.json")
    mark("r15-w3-ex3")


if __name__ == "__main__":
    main()
