#!/usr/bin/env python3
"""Round 19 · Final: generate a minimal ML loop project package."""

from __future__ import annotations

import ast
import csv
import json
import shutil
import subprocess
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[3]
LAB = Path.home() / "cli-lab" / "round19" / "final_auto" / "ml_minimal_loop_lab"

README = """# Round 19 ML minimal loop lab

Generated by the Web UI final exercise.

Files:

- `data/toy_classification.csv`: small labeled dataset.
- `training.py`: scikit-learn-style train/test split, Pipeline, fit, predict, evaluate flow.
- `metrics.py`: small metric helpers and confusion-count vocabulary.
- `preprocess.py`: preprocessing rules that prevent leakage.
- `experiment_contract.json`: required workflow and outputs.
- `stdlib_smoke.py`: dependency-free smoke check used by Web UI.
- `final_static_check.py`: AST and contract verification.
"""

TRAINING = '''"""Round 19 final ML training loop."""

from __future__ import annotations

import json
from pathlib import Path

import pandas as pd
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report


DATA_PATH = Path("data/toy_classification.csv")
REPORT_DIR = Path("reports")


def load_data(path: Path = DATA_PATH):
    df = pd.read_csv(path)
    X = df[["length", "score", "source_weight"]]
    y = df["label"]
    return X, y


def split_data(X, y):
    return train_test_split(X, y, test_size=0.25, random_state=42, stratify=y)


def build_pipeline() -> Pipeline:
    return Pipeline([
        ("scaler", StandardScaler()),
        ("model", LogisticRegression(max_iter=1000, random_state=42)),
    ])


def train_model(X_train, y_train) -> Pipeline:
    model = build_pipeline()
    model.fit(X_train, y_train)
    return model


def evaluate_model(model: Pipeline, X_test, y_test) -> dict:
    y_pred = model.predict(X_test)
    return {
        "accuracy": round(float(accuracy_score(y_test, y_pred)), 3),
        "precision": round(float(precision_score(y_test, y_pred, average="macro", zero_division=0)), 3),
        "recall": round(float(recall_score(y_test, y_pred, average="macro", zero_division=0)), 3),
        "f1": round(float(f1_score(y_test, y_pred, average="macro", zero_division=0)), 3),
        "report": classification_report(y_test, y_pred, zero_division=0),
    }


def run_experiment() -> dict:
    X, y = load_data()
    X_train, X_test, y_train, y_test = split_data(X, y)
    model = train_model(X_train, y_train)
    metrics = evaluate_model(model, X_test, y_test)
    cv_scores = cross_val_score(build_pipeline(), X, y, cv=3)
    result = {
        "rows": int(len(y)),
        "train_rows": int(len(y_train)),
        "test_rows": int(len(y_test)),
        "metrics": metrics,
        "cv_mean": round(float(cv_scores.mean()), 3),
    }
    REPORT_DIR.mkdir(exist_ok=True)
    (REPORT_DIR / "metrics.json").write_text(json.dumps(result, ensure_ascii=False, indent=2), encoding="utf-8")
    return result


if __name__ == "__main__":
    print(json.dumps(run_experiment(), ensure_ascii=False, indent=2))
'''

METRICS = '''"""Metric vocabulary for Round 19."""


def binary_metrics(tp: int, fp: int, fn: int, tn: int) -> dict:
    accuracy = (tp + tn) / (tp + fp + fn + tn)
    precision = tp / (tp + fp)
    recall = tp / (tp + fn)
    f1 = 2 * precision * recall / (precision + recall)
    return {
        "accuracy": round(accuracy, 3),
        "precision": round(precision, 3),
        "recall": round(recall, 3),
        "f1": round(f1, 3),
    }


METRIC_HINTS = {
    "accuracy": "overall correctness",
    "precision": "trustworthiness of positive predictions",
    "recall": "coverage of actual positives",
    "f1": "balanced precision and recall",
}
'''

PREPROCESS = '''"""Preprocessing rules that prevent data leakage."""


RULES = [
    "split data before fitting preprocessors",
    "fit scaler on X_train only",
    "transform X_train and X_test with the same fitted scaler",
    "wrap scaler and model in Pipeline when possible",
]


WRONG_PATTERN = "scaler.fit(X) before split"
RIGHT_PATTERN = "Pipeline([('scaler', StandardScaler()), ('model', LogisticRegression())])"
'''

STDLIB_SMOKE = '''#!/usr/bin/env python3
"""Dependency-free smoke check for the generated ML project."""

from __future__ import annotations

import csv
import json
from pathlib import Path


base = Path(__file__).resolve().parent
with (base / "data" / "toy_classification.csv").open("r", encoding="utf-8", newline="") as f:
    rows = list(csv.DictReader(f))

features = [[float(row["length"]), float(row["score"]), float(row["source_weight"])] for row in rows]
labels = [row["label"] for row in rows]
split_at = 9
train_features, test_features = features[:split_at], features[split_at:]
train_labels, test_labels = labels[:split_at], labels[split_at:]

label_centroids = {}
for row, label in zip(train_features, train_labels):
    label_centroids.setdefault(label, []).append(sum(row))
centroids = {
    label: sum(values) / len(values)
    for label, values in label_centroids.items()
}

def predict(row: list[float]) -> str:
    score = sum(row)
    return min(centroids, key=lambda label: abs(score - centroids[label]))

predictions = [predict(row) for row in test_features]
correct = sum(1 for expected, actual in zip(test_labels, predictions) if expected == actual)
summary = {
    "rows": len(rows),
    "train_rows": len(train_features),
    "test_rows": len(test_features),
    "labels": sorted(set(labels)),
    "predictions": predictions,
    "accuracy": round(correct / len(test_labels), 3),
    "workflow": ["load", "split", "fit", "predict", "evaluate"],
}
(base / "reports").mkdir(exist_ok=True)
(base / "reports" / "stdlib_smoke.json").write_text(json.dumps(summary, ensure_ascii=False, indent=2) + "\\n", encoding="utf-8")
print(json.dumps(summary, ensure_ascii=False, sort_keys=True))
'''

CONTRACT = {
    "project": "round19_ml_minimal_loop_lab",
    "inputs": ["data/toy_classification.csv"],
    "required_columns": ["id", "length", "score", "source_weight", "label"],
    "workflow": ["load_data", "split_data", "build_pipeline", "train_model", "evaluate_model", "run_experiment"],
    "metrics": ["accuracy", "precision", "recall", "f1"],
    "leakage_rules": ["fit preprocessors on train only", "use Pipeline for preprocessing plus model"],
    "outputs": ["reports/metrics.json", "reports/stdlib_smoke.json", "round19_final_summary.json"],
}

DATA_ROWS = [
    {"id": 1, "length": "1.0", "score": "0.10", "source_weight": "0.2", "label": "low"},
    {"id": 2, "length": "1.2", "score": "0.20", "source_weight": "0.3", "label": "low"},
    {"id": 3, "length": "1.4", "score": "0.15", "source_weight": "0.2", "label": "low"},
    {"id": 4, "length": "2.0", "score": "0.70", "source_weight": "0.6", "label": "mid"},
    {"id": 5, "length": "2.2", "score": "0.80", "source_weight": "0.7", "label": "mid"},
    {"id": 6, "length": "2.4", "score": "0.75", "source_weight": "0.6", "label": "mid"},
    {"id": 7, "length": "3.0", "score": "1.40", "source_weight": "0.9", "label": "high"},
    {"id": 8, "length": "3.1", "score": "1.50", "source_weight": "1.0", "label": "high"},
    {"id": 9, "length": "3.2", "score": "1.55", "source_weight": "0.95", "label": "high"},
    {"id": 10, "length": "1.1", "score": "0.18", "source_weight": "0.25", "label": "low"},
    {"id": 11, "length": "2.3", "score": "0.85", "source_weight": "0.65", "label": "mid"},
    {"id": 12, "length": "3.3", "score": "1.60", "source_weight": "0.98", "label": "high"},
]

FINAL_CHECK = '''#!/usr/bin/env python3
"""Static final checks for Round 19 ML minimal loop lab."""

from __future__ import annotations

import ast
import csv
import json
import subprocess
import sys
from pathlib import Path


base = Path(__file__).resolve().parent
training = (base / "training.py").read_text(encoding="utf-8")
metrics = (base / "metrics.py").read_text(encoding="utf-8")
preprocess = (base / "preprocess.py").read_text(encoding="utf-8")
stdlib = (base / "stdlib_smoke.py").read_text(encoding="utf-8")
for source in (training, metrics, preprocess, stdlib):
    ast.parse(source)

contract = json.loads((base / "experiment_contract.json").read_text(encoding="utf-8"))
with (base / "data" / "toy_classification.csv").open("r", encoding="utf-8", newline="") as f:
    rows = list(csv.DictReader(f))

proc = subprocess.run([sys.executable, "stdlib_smoke.py"], cwd=base, capture_output=True, text=True, check=False)
smoke = {}
if proc.returncode == 0:
    smoke = json.loads((base / "reports" / "stdlib_smoke.json").read_text(encoding="utf-8"))

checks = {
    "files_exist": all((base / path).exists() for path in ("README.md", "training.py", "metrics.py", "preprocess.py", "experiment_contract.json", "stdlib_smoke.py", "data/toy_classification.csv")),
    "workflow_functions": all(f"def {name}" in training for name in contract["workflow"]),
    "split_and_pipeline": all(text in training for text in ("train_test_split", "test_size=0.25", "random_state=42", "Pipeline", "StandardScaler", "LogisticRegression")),
    "metric_calls": all(text in training for text in ("accuracy_score", "precision_score", "recall_score", "f1_score", "classification_report")),
    "cross_validation": "cross_val_score" in training and "cv=3" in training,
    "metric_helper": all(text in metrics for text in ("binary_metrics", "precision", "recall", "f1")),
    "leakage_rules": "split data before fitting preprocessors" in preprocess and "scaler.fit(X) before split" in preprocess,
    "data_contract": len(rows) == 12 and set(rows[0]) == set(contract["required_columns"]),
    "stdlib_smoke": proc.returncode == 0 and smoke.get("rows") == 12 and smoke.get("test_rows") == 3,
    "contract_metrics": set(contract.get("metrics", [])) == {"accuracy", "precision", "recall", "f1"},
}
report = {"ok": all(checks.values()), "checks": checks, "smoke": smoke, "stderr": proc.stderr.strip()}
(base / "round19_final_summary.json").write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\\n", encoding="utf-8")
print(json.dumps(report, ensure_ascii=False, sort_keys=True))
raise SystemExit(0 if report["ok"] else 1)
'''


def mark(task_id: str) -> None:
    subprocess.run(["bash", str(REPO_ROOT / "mark_done.sh"), task_id], cwd=REPO_ROOT, check=True)


def reset_lab() -> None:
    if LAB.exists():
        shutil.rmtree(LAB)
    (LAB / "data").mkdir(parents=True)
    (LAB / "reports").mkdir(parents=True)


def write_csv(path: Path) -> None:
    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=["id", "length", "score", "source_weight", "label"])
        writer.writeheader()
        writer.writerows(DATA_ROWS)


def main() -> None:
    reset_lab()
    (LAB / "README.md").write_text(README, encoding="utf-8")
    (LAB / "training.py").write_text(TRAINING, encoding="utf-8")
    (LAB / "metrics.py").write_text(METRICS, encoding="utf-8")
    (LAB / "preprocess.py").write_text(PREPROCESS, encoding="utf-8")
    (LAB / "stdlib_smoke.py").write_text(STDLIB_SMOKE, encoding="utf-8")
    (LAB / "experiment_contract.json").write_text(json.dumps(CONTRACT, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    write_csv(LAB / "data" / "toy_classification.csv")
    check = LAB / "final_static_check.py"
    check.write_text(FINAL_CHECK, encoding="utf-8")
    check.chmod(0o755)
    proc = subprocess.run(["python3", str(check)], cwd=LAB, capture_output=True, text=True, check=False)
    if proc.returncode != 0:
        raise RuntimeError(proc.stderr or proc.stdout)
    print("Round 19 Final 机器学习最小闭环项目包")
    print("sandbox:", LAB)
    print("contract:", LAB / "experiment_contract.json")
    print("report:", LAB / "round19_final_summary.json")
    mark("r19-fin-comp")


if __name__ == "__main__":
    main()
