#!/bin/bash
# =============================================================
# mark_done.sh — 标记任务完成，同时写入 progress.json 和 progress_data.js
#
# 用法：
#   bash mark_done.sh <task-id>           标记完成
#   bash mark_done.sh <task-id> --undo    取消完成
#   bash mark_done.sh                     查看所有任务状态
#
# 示例：
#   bash mark_done.sh w1-read
#   bash mark_done.sh w1-ex1 --undo
# =============================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROGRESS_FILE="$SCRIPT_DIR/progress.json"
PROGRESS_JS="$SCRIPT_DIR/progress_data.js"

if [ ! -f "$PROGRESS_FILE" ]; then
  echo "❌ 找不到 progress.json，请确认你在仓库根目录"
  exit 1
fi

TASK_ID="$1"
MODE="${2:-}"

# ── 无参数：显示状态概览 ──────────────────────────────────────
if [ -z "$TASK_ID" ]; then
  echo "用法：bash mark_done.sh <task-id> [--undo]"
  echo ""
  python3 - <<'PYEOF'
import json
with open("progress.json") as f:
    data = json.load(f)
tasks = data.get("tasks", {})
done   = [(k, v["done_at"]) for k, v in tasks.items() if v["done"]]
undone = [k for k, v in tasks.items() if not v["done"]]
print(f"✅ 已完成 ({len(done)}/{len(tasks)}):")
for k, ts in done:
    print(f"   {k}  ({ts})")
if undone:
    print(f"\n⬜ 未完成 ({len(undone)}):")
    for k in undone:
        print(f"   {k}")
PYEOF
  exit 0
fi

# ── 标记 / 取消 ───────────────────────────────────────────────
python3 - "$SCRIPT_DIR" "$TASK_ID" "$MODE" <<'PYEOF'
import json, sys, datetime, textwrap

script_dir = sys.argv[1]
task_id    = sys.argv[2]
mode       = sys.argv[3] if len(sys.argv) > 3 else ""

json_path = f"{script_dir}/progress.json"
js_path   = f"{script_dir}/progress_data.js"

with open(json_path, "r", encoding="utf-8") as f:
    data = json.load(f)

tasks = data.get("tasks", {})

if task_id not in tasks:
    print(f"❌ 未知任务 ID：{task_id}")
    print("   已知 ID：" + ", ".join(tasks.keys()))
    sys.exit(1)

if mode == "--undo":
    tasks[task_id]["done"]    = False
    tasks[task_id]["done_at"] = None
    print(f"↩️  已取消完成：{task_id}")
else:
    if tasks[task_id]["done"]:
        ts = tasks[task_id]["done_at"]
        print(f"✅ 已是完成状态（{ts}），无需重复标记")
    else:
        now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
        tasks[task_id]["done"]    = True
        tasks[task_id]["done_at"] = now
        print(f"✅ 已标记完成：{task_id}  ({now})")

# 写回 progress.json
with open(json_path, "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

# 同步写 progress_data.js（供 file:// 双击打开 progress.html 使用）
tasks_js = json.dumps(data["tasks"], ensure_ascii=False, indent=4)
js_content = f"""// Auto-generated by mark_done.sh — DO NOT edit manually
// Source of truth: progress.json
window.PROGRESS_DATA = {{
  "version": {data.get('version', 1)},
  "tasks": {tasks_js}
}};
"""
with open(js_path, "w", encoding="utf-8") as f:
    f.write(js_content)

total      = len(tasks)
done_count = sum(1 for v in tasks.values() if v["done"])
print(f"📊 总进度：{done_count}/{total}")
PYEOF
