// Auto-generated by scripts/build_rounds_data.py
window.ROUNDS_DATA = [
  {
    "id": "round_00",
    "title": "Round 00 · Terminal 初见与学习系统搭建",
    "lane": "engineering",
    "difficulty": "⭐☆☆☆☆",
    "duration": "3 周",
    "weeks": [
      {
        "id": "week1",
        "title": "第 1 周：建立感觉（pwd / ls / cd）",
        "tasks": [
          {
            "id": "w1-read",
            "type": "reading",
            "title": "阅读 week1/notes.md",
            "file": "rounds/round_00/week1/notes.md"
          },
          {
            "id": "w1-ex1",
            "type": "exercise",
            "title": "练习1：认识当前位置",
            "file": "rounds/round_00/week1/exercises.sh"
          },
          {
            "id": "w1-ex2",
            "type": "exercise",
            "title": "练习2：创建子目录并切换",
            "file": "rounds/round_00/week1/exercises.sh"
          },
          {
            "id": "w1-ex3",
            "type": "exercise",
            "title": "练习3：绝对路径 vs 相对路径",
            "file": "rounds/round_00/week1/exercises.sh"
          },
          {
            "id": "w1-self",
            "type": "test",
            "title": "第1周自测",
            "file": "rounds/round_00/week1/exercises.sh"
          }
        ]
      },
      {
        "id": "week2",
        "title": "第 2 周：创建东西（mkdir / touch / cat）",
        "tasks": [
          {
            "id": "w2-read",
            "type": "reading",
            "title": "阅读 week2/notes.md",
            "file": "rounds/round_00/week2/notes.md"
          },
          {
            "id": "w2-ex4",
            "type": "exercise",
            "title": "练习4：创建更多子目录",
            "file": "rounds/round_00/week2/exercises.sh"
          },
          {
            "id": "w2-ex5",
            "type": "exercise",
            "title": "练习5：创建空文件",
            "file": "rounds/round_00/week2/exercises.sh"
          },
          {
            "id": "w2-ex6",
            "type": "exercise",
            "title": "练习6：用 cat 查看空文件",
            "file": "rounds/round_00/week2/exercises.sh"
          },
          {
            "id": "w2-ex7",
            "type": "exercise",
            "title": "练习7：echo + cat",
            "file": "rounds/round_00/week2/exercises.sh"
          },
          {
            "id": "w2-self",
            "type": "test",
            "title": "第2周自测",
            "file": "rounds/round_00/week2/exercises.sh"
          }
        ]
      },
      {
        "id": "week3",
        "title": "第 3 周：学会自查（man）",
        "tasks": [
          {
            "id": "w3-read",
            "type": "reading",
            "title": "阅读 week3/notes.md",
            "file": "rounds/round_00/week3/notes.md"
          },
          {
            "id": "w3-ex8",
            "type": "exercise",
            "title": "练习8：man ls",
            "file": "rounds/round_00/week3/exercises.sh"
          },
          {
            "id": "w3-ex9",
            "type": "exercise",
            "title": "练习9：man pwd/mkdir/touch/cat",
            "file": "rounds/round_00/week3/exercises.sh"
          },
          {
            "id": "w3-ex10",
            "type": "exercise",
            "title": "练习10：man man",
            "file": "rounds/round_00/week3/exercises.sh"
          },
          {
            "id": "w3-self",
            "type": "test",
            "title": "第3周自测",
            "file": "rounds/round_00/week3/exercises.sh"
          }
        ]
      },
      {
        "id": "final",
        "title": "最终验收",
        "tasks": [
          {
            "id": "fin-comp",
            "type": "exercise",
            "title": "综合练习",
            "file": "rounds/round_00/final/comprehensive_exercise.sh"
          },
          {
            "id": "fin-sheet",
            "type": "output",
            "title": "完成命令小抄",
            "file": "rounds/round_00/final/command_cheatsheet.md"
          },
          {
            "id": "fin-acc1",
            "type": "test",
            "title": "验收：Terminal 与 Shell 的区别",
            "file": "round_00.md"
          },
          {
            "id": "fin-acc2",
            "type": "test",
            "title": "验收：能用 7 个命令",
            "file": "round_00.md"
          },
          {
            "id": "fin-acc3",
            "type": "output",
            "title": "验收：cli-lab 目录与小抄存在",
            "file": "round_00.md"
          }
        ]
      }
    ]
  },
  {
    "id": "round_01",
    "title": "Round 01 · 文件系统与基础命令",
    "lane": "engineering",
    "difficulty": "⭐☆☆☆☆",
    "duration": "3 周",
    "weeks": [
      {
        "id": "round01-week1",
        "title": "第 1 周：路径感",
        "tasks": [
          {
            "id": "r01-w1-read",
            "type": "reading",
            "title": "阅读：路径、绝对路径、相对路径",
            "file": "rounds/round_01/week1/notes.md"
          },
          {
            "id": "r01-w1-ex1",
            "type": "exercise",
            "title": "练习：路径切换实验",
            "file": "rounds/round_01/week1/exercises.sh"
          },
          {
            "id": "r01-w1-self",
            "type": "test",
            "title": "自测：不用提示切换目录",
            "file": "rounds/round_01/week1/exercises.sh"
          }
        ]
      },
      {
        "id": "round01-week2",
        "title": "第 2 周：文件操作",
        "tasks": [
          {
            "id": "r01-w2-read",
            "type": "reading",
            "title": "阅读：创建、复制、移动、删除",
            "file": "rounds/round_01/week2/notes.md"
          },
          {
            "id": "r01-w2-ex2",
            "type": "exercise",
            "title": "练习：创建 / 复制 / 改名 / 删除",
            "file": "rounds/round_01/week2/exercises.sh"
          },
          {
            "id": "r01-w2-self",
            "type": "test",
            "title": "自测：独立整理 week2_test",
            "file": "rounds/round_01/week2/exercises.sh"
          }
        ]
      },
      {
        "id": "round01-week3",
        "title": "第 3 周：查看文本与帮助",
        "tasks": [
          {
            "id": "r01-w3-read",
            "type": "reading",
            "title": "阅读：cat / less / head / tail / man",
            "file": "rounds/round_01/week3/notes.md"
          },
          {
            "id": "r01-w3-ex3",
            "type": "exercise",
            "title": "练习：查看文本与查帮助",
            "file": "rounds/round_01/week3/exercises.sh"
          },
          {
            "id": "r01-w3-self",
            "type": "test",
            "title": "自测：head / tail / man",
            "file": "rounds/round_01/week3/exercises.sh"
          }
        ]
      },
      {
        "id": "round01-final",
        "title": "最终验收",
        "tasks": [
          {
            "id": "r01-fin-comp",
            "type": "exercise",
            "title": "综合练习：迷你文件整理实验室",
            "file": "rounds/round_01/final/comprehensive_exercise.sh"
          },
          {
            "id": "r01-fin-sheet",
            "type": "output",
            "title": "产出：完成 Round 01 命令小抄",
            "file": "rounds/round_01/final/command_cheatsheet.md"
          },
          {
            "id": "r01-fin-acc1",
            "type": "test",
            "title": "验收：解释路径与 13 个基础命令",
            "file": "round_01.md"
          }
        ]
      }
    ]
  },
  {
    "id": "round_02",
    "title": "Round 02 · Shell、管道、Git 最小工作流",
    "lane": "engineering",
    "difficulty": "⭐⭐☆☆☆",
    "duration": "3 周",
    "weeks": [
      {
        "id": "round02-week1",
        "title": "第 1 周：重定向与管道",
        "tasks": [
          {
            "id": "r02-w1-read",
            "type": "reading",
            "title": "阅读：重定向、追加、管道",
            "file": "rounds/round_02/week1/notes.md"
          },
          {
            "id": "r02-w1-ex1",
            "type": "exercise",
            "title": "练习：覆盖与追加",
            "file": "rounds/round_02/week1/exercises.sh"
          },
          {
            "id": "r02-w1-ex2",
            "type": "exercise",
            "title": "练习：去重统计",
            "file": "rounds/round_02/week1/exercises.sh"
          },
          {
            "id": "r02-w1-ex3",
            "type": "exercise",
            "title": "练习：日志过滤流水线",
            "file": "rounds/round_02/week1/exercises.sh"
          },
          {
            "id": "r02-w1-self",
            "type": "test",
            "title": "自测：独立写日志统计链",
            "file": "rounds/round_02/week1/exercises.sh"
          }
        ]
      },
      {
        "id": "round02-week2",
        "title": "第 2 周：最小 shell 脚本",
        "tasks": [
          {
            "id": "r02-w2-read",
            "type": "reading",
            "title": "阅读：最小 Shell 脚本与参数",
            "file": "rounds/round_02/week2/notes.md"
          },
          {
            "id": "r02-w2-ex4",
            "type": "exercise",
            "title": "练习：count_errors.sh",
            "file": "rounds/round_02/week2/exercises.sh"
          },
          {
            "id": "r02-w2-ex5",
            "type": "exercise",
            "title": "练习：count_labels.sh",
            "file": "rounds/round_02/week2/exercises.sh"
          },
          {
            "id": "r02-w2-ex6",
            "type": "exercise",
            "title": "练习：show_args.sh 参数观察",
            "file": "rounds/round_02/week2/exercises.sh"
          },
          {
            "id": "r02-w2-self",
            "type": "test",
            "title": "自测：运行并解释参数脚本",
            "file": "rounds/round_02/week2/exercises.sh"
          }
        ]
      },
      {
        "id": "round02-week3",
        "title": "第 3 周：Git 最小工作流",
        "tasks": [
          {
            "id": "r02-w3-read",
            "type": "reading",
            "title": "阅读：Git 工作区、暂存区、提交历史",
            "file": "rounds/round_02/week3/notes.md"
          },
          {
            "id": "r02-w3-ex7",
            "type": "exercise",
            "title": "练习：初始化与首次提交",
            "file": "rounds/round_02/week3/exercises.sh"
          },
          {
            "id": "r02-w3-ex8",
            "type": "exercise",
            "title": "练习：修改 README 后第二次提交",
            "file": "rounds/round_02/week3/exercises.sh"
          },
          {
            "id": "r02-w3-ex9",
            "type": "exercise",
            "title": "练习：新增 notes.txt 再提交",
            "file": "rounds/round_02/week3/exercises.sh"
          },
          {
            "id": "r02-w3-self",
            "type": "test",
            "title": "自测：解释 status 与 log",
            "file": "rounds/round_02/week3/exercises.sh"
          }
        ]
      },
      {
        "id": "round02-final",
        "title": "最终验收",
        "tasks": [
          {
            "id": "r02-fin-comp",
            "type": "exercise",
            "title": "综合练习：日志统计器 + 本地 Git 仓库",
            "file": "rounds/round_02/final/comprehensive_exercise.sh"
          },
          {
            "id": "r02-fin-sheet",
            "type": "output",
            "title": "产出：完成 Round 02 命令小抄",
            "file": "rounds/round_02/final/command_cheatsheet.md"
          },
          {
            "id": "r02-fin-acc1",
            "type": "test",
            "title": "验收：解释重定向、管道、脚本参数",
            "file": "round_02.md"
          },
          {
            "id": "r02-fin-acc2",
            "type": "output",
            "title": "验收：解释 3 次本地 Git 提交",
            "file": "round_02.md"
          }
        ]
      }
    ]
  },
  {
    "id": "round_03",
    "title": "Round 03 · Python 基础补强 + 复杂度直觉",
    "lane": "engineering",
    "difficulty": "⭐⭐☆☆☆",
    "duration": "3 周",
    "weeks": [
      {
        "id": "round03-week1",
        "title": "第 1 周：Python 基础语法",
        "tasks": [
          {
            "id": "r03-w1-read",
            "type": "reading",
            "title": "阅读 week1/notes.md",
            "file": "rounds/round_03/week1/notes.md"
          },
          {
            "id": "r03-w1-ex1",
            "type": "exercise",
            "title": "练习1",
            "file": "rounds/round_03/week1/exercises.sh"
          },
          {
            "id": "r03-w1-self",
            "type": "test",
            "title": "第1周自测",
            "file": "rounds/round_03/week1/exercises.sh"
          }
        ]
      },
      {
        "id": "round03-week2",
        "title": "第 2 周：list/dict 与函数拆分",
        "tasks": [
          {
            "id": "r03-w2-read",
            "type": "reading",
            "title": "阅读 week2/notes.md",
            "file": "rounds/round_03/week2/notes.md"
          },
          {
            "id": "r03-w2-ex2",
            "type": "exercise",
            "title": "练习2",
            "file": "rounds/round_03/week2/exercises.sh"
          },
          {
            "id": "r03-w2-self",
            "type": "test",
            "title": "第2周自测",
            "file": "rounds/round_03/week2/exercises.sh"
          }
        ]
      },
      {
        "id": "round03-week3",
        "title": "第 3 周：复杂度观察",
        "tasks": [
          {
            "id": "r03-w3-read",
            "type": "reading",
            "title": "阅读 week3/notes.md",
            "file": "rounds/round_03/week3/notes.md"
          },
          {
            "id": "r03-w3-ex3",
            "type": "exercise",
            "title": "练习3",
            "file": "rounds/round_03/week3/exercises.sh"
          },
          {
            "id": "r03-w3-self",
            "type": "test",
            "title": "第3周自测",
            "file": "rounds/round_03/week3/exercises.sh"
          }
        ]
      },
      {
        "id": "round03-final",
        "title": "最终验收",
        "tasks": [
          {
            "id": "r03-fin-comp",
            "type": "exercise",
            "title": "综合练习",
            "file": "rounds/round_03/final/comprehensive_exercise.sh"
          },
          {
            "id": "r03-fin-sheet",
            "type": "output",
            "title": "完成本 Round 小抄",
            "file": "rounds/round_03/final/complexity_cheatsheet.md"
          },
          {
            "id": "r03-fin-acc1",
            "type": "test",
            "title": "验收：Round 03 核心目标",
            "file": "round_03.md"
          }
        ]
      }
    ]
  },
  {
    "id": "round_04",
    "title": "Round 04 · 核心数据结构",
    "lane": "engineering",
    "difficulty": "⭐⭐⭐☆☆",
    "duration": "3 周",
    "weeks": [
      {
        "id": "round04-week1",
        "title": "第 1 周：列表与顺序存储",
        "tasks": [
          {
            "id": "r04-w1-read",
            "type": "reading",
            "title": "阅读 week1/notes.md",
            "file": "rounds/round_04/week1/notes.md"
          },
          {
            "id": "r04-w1-ex1",
            "type": "exercise",
            "title": "练习1",
            "file": "rounds/round_04/week1/exercises.sh"
          },
          {
            "id": "r04-w1-self",
            "type": "test",
            "title": "第1周自测",
            "file": "rounds/round_04/week1/exercises.sh"
          }
        ]
      },
      {
        "id": "round04-week2",
        "title": "第 2 周：栈与队列",
        "tasks": [
          {
            "id": "r04-w2-read",
            "type": "reading",
            "title": "阅读 week2/notes.md",
            "file": "rounds/round_04/week2/notes.md"
          },
          {
            "id": "r04-w2-ex2",
            "type": "exercise",
            "title": "练习2",
            "file": "rounds/round_04/week2/exercises.sh"
          },
          {
            "id": "r04-w2-self",
            "type": "test",
            "title": "第2周自测",
            "file": "rounds/round_04/week2/exercises.sh"
          }
        ]
      },
      {
        "id": "round04-week3",
        "title": "第 3 周：哈希与去重",
        "tasks": [
          {
            "id": "r04-w3-read",
            "type": "reading",
            "title": "阅读 week3/notes.md",
            "file": "rounds/round_04/week3/notes.md"
          },
          {
            "id": "r04-w3-ex3",
            "type": "exercise",
            "title": "练习3",
            "file": "rounds/round_04/week3/exercises.sh"
          },
          {
            "id": "r04-w3-self",
            "type": "test",
            "title": "第3周自测",
            "file": "rounds/round_04/week3/exercises.sh"
          }
        ]
      },
      {
        "id": "round04-final",
        "title": "最终验收",
        "tasks": [
          {
            "id": "r04-fin-comp",
            "type": "exercise",
            "title": "综合练习",
            "file": "rounds/round_04/final/comprehensive_exercise.sh"
          },
          {
            "id": "r04-fin-sheet",
            "type": "output",
            "title": "完成本 Round 小抄",
            "file": "rounds/round_04/final/complexity_cheatsheet.md"
          },
          {
            "id": "r04-fin-acc1",
            "type": "test",
            "title": "验收：Round 04 核心目标",
            "file": "round_04.md"
          }
        ]
      }
    ]
  },
  {
    "id": "round_05",
    "title": "Round 05 · 高频算法模式",
    "lane": "engineering",
    "difficulty": "⭐⭐⭐☆☆",
    "duration": "3 周",
    "weeks": [
      {
        "id": "round05-week1",
        "title": "第 1 周：双指针 / 滑动窗口 / 二分",
        "tasks": [
          {
            "id": "r05-w1-read",
            "type": "reading",
            "title": "阅读 week1/notes.md",
            "file": "rounds/round_05/week1/notes.md"
          },
          {
            "id": "r05-w1-ex1",
            "type": "exercise",
            "title": "练习1",
            "file": "rounds/round_05/week1/exercises.sh"
          },
          {
            "id": "r05-w1-self",
            "type": "test",
            "title": "第1周自测",
            "file": "rounds/round_05/week1/exercises.sh"
          }
        ]
      },
      {
        "id": "round05-week2",
        "title": "第 2 周：分治 / DFS / BFS / 回溯",
        "tasks": [
          {
            "id": "r05-w2-read",
            "type": "reading",
            "title": "阅读 week2/notes.md",
            "file": "rounds/round_05/week2/notes.md"
          },
          {
            "id": "r05-w2-ex2",
            "type": "exercise",
            "title": "练习2",
            "file": "rounds/round_05/week2/exercises.sh"
          },
          {
            "id": "r05-w2-self",
            "type": "test",
            "title": "第2周自测",
            "file": "rounds/round_05/week2/exercises.sh"
          }
        ]
      },
      {
        "id": "round05-week3",
        "title": "第 3 周：贪心 / DP 入门",
        "tasks": [
          {
            "id": "r05-w3-read",
            "type": "reading",
            "title": "阅读 week3/notes.md",
            "file": "rounds/round_05/week3/notes.md"
          },
          {
            "id": "r05-w3-ex3",
            "type": "exercise",
            "title": "练习3",
            "file": "rounds/round_05/week3/exercises.sh"
          },
          {
            "id": "r05-w3-self",
            "type": "test",
            "title": "第3周自测",
            "file": "rounds/round_05/week3/exercises.sh"
          }
        ]
      },
      {
        "id": "round05-final",
        "title": "最终验收",
        "tasks": [
          {
            "id": "r05-fin-comp",
            "type": "exercise",
            "title": "综合练习",
            "file": "rounds/round_05/final/comprehensive_exercise.sh"
          },
          {
            "id": "r05-fin-sheet",
            "type": "output",
            "title": "完成本 Round 小抄",
            "file": "rounds/round_05/final/algorithm_patterns_cheatsheet.md"
          },
          {
            "id": "r05-fin-acc1",
            "type": "test",
            "title": "验收：Round 05 核心目标",
            "file": "round_05.md"
          }
        ]
      }
    ]
  },
  {
    "id": "round_06",
    "title": "Round 06 · Linux 进阶与自动化",
    "lane": "engineering",
    "difficulty": "⭐⭐☆☆☆",
    "duration": "3 周",
    "weeks": [
      {
        "id": "round06-week1",
        "title": "第 1 周：基础练习",
        "tasks": [
          {
            "id": "r06-w1-read",
            "type": "reading",
            "title": "阅读 week1/notes.md",
            "file": "rounds/round_06/week1/notes.md"
          },
          {
            "id": "r06-w1-ex1",
            "type": "exercise",
            "title": "练习1",
            "file": "rounds/round_06/week1/exercises.sh"
          },
          {
            "id": "r06-w1-self",
            "type": "test",
            "title": "第1周自测",
            "file": "rounds/round_06/week1/exercises.sh"
          }
        ]
      },
      {
        "id": "round06-week2",
        "title": "第 2 周：进阶练习",
        "tasks": [
          {
            "id": "r06-w2-read",
            "type": "reading",
            "title": "阅读 week2/notes.md",
            "file": "rounds/round_06/week2/notes.md"
          },
          {
            "id": "r06-w2-ex2",
            "type": "exercise",
            "title": "练习2",
            "file": "rounds/round_06/week2/exercises.sh"
          },
          {
            "id": "r06-w2-self",
            "type": "test",
            "title": "第2周自测",
            "file": "rounds/round_06/week2/exercises.sh"
          }
        ]
      },
      {
        "id": "round06-week3",
        "title": "第 3 周：综合练习",
        "tasks": [
          {
            "id": "r06-w3-read",
            "type": "reading",
            "title": "阅读 week3/notes.md",
            "file": "rounds/round_06/week3/notes.md"
          },
          {
            "id": "r06-w3-ex3",
            "type": "exercise",
            "title": "练习3",
            "file": "rounds/round_06/week3/exercises.sh"
          },
          {
            "id": "r06-w3-self",
            "type": "test",
            "title": "第3周自测",
            "file": "rounds/round_06/week3/exercises.sh"
          }
        ]
      },
      {
        "id": "round06-final",
        "title": "最终验收",
        "tasks": [
          {
            "id": "r06-fin-comp",
            "type": "exercise",
            "title": "综合练习",
            "file": "rounds/round_06/final/comprehensive_exercise.sh"
          },
          {
            "id": "r06-fin-sheet",
            "type": "output",
            "title": "完成本 Round 小抄",
            "file": "rounds/round_06/final/linux_automation_cheatsheet.md"
          },
          {
            "id": "r06-fin-acc1",
            "type": "test",
            "title": "验收：Round 06 核心目标",
            "file": "round_06.md"
          }
        ]
      }
    ]
  },
  {
    "id": "round_07",
    "title": "Round 07 · 面向 AI 项目的综合练习",
    "lane": "engineering",
    "difficulty": "⭐⭐⭐☆☆",
    "duration": "3 周",
    "weeks": [
      {
        "id": "round07-week1",
        "title": "第 1 周：基础练习",
        "tasks": [
          {
            "id": "r07-w1-read",
            "type": "reading",
            "title": "阅读 week1/notes.md",
            "file": "rounds/round_07/week1/notes.md"
          },
          {
            "id": "r07-w1-ex1",
            "type": "exercise",
            "title": "练习1",
            "file": "rounds/round_07/week1/exercises.py"
          },
          {
            "id": "r07-w1-self",
            "type": "test",
            "title": "第1周自测",
            "file": "rounds/round_07/week1/exercises.py"
          }
        ]
      },
      {
        "id": "round07-week2",
        "title": "第 2 周：进阶练习",
        "tasks": [
          {
            "id": "r07-w2-read",
            "type": "reading",
            "title": "阅读 week2/notes.md",
            "file": "rounds/round_07/week2/notes.md"
          },
          {
            "id": "r07-w2-ex2",
            "type": "exercise",
            "title": "练习2",
            "file": "rounds/round_07/week2/exercises.py"
          },
          {
            "id": "r07-w2-self",
            "type": "test",
            "title": "第2周自测",
            "file": "rounds/round_07/week2/exercises.py"
          }
        ]
      },
      {
        "id": "round07-week3",
        "title": "第 3 周：综合练习",
        "tasks": [
          {
            "id": "r07-w3-read",
            "type": "reading",
            "title": "阅读 week3/notes.md",
            "file": "rounds/round_07/week3/notes.md"
          },
          {
            "id": "r07-w3-ex3",
            "type": "exercise",
            "title": "练习3",
            "file": "rounds/round_07/week3/exercises.py"
          },
          {
            "id": "r07-w3-self",
            "type": "test",
            "title": "第3周自测",
            "file": "rounds/round_07/week3/exercises.py"
          }
        ]
      },
      {
        "id": "round07-final",
        "title": "最终验收",
        "tasks": [
          {
            "id": "r07-fin-comp",
            "type": "exercise",
            "title": "综合练习",
            "file": "rounds/round_07/final/comprehensive_exercise.py"
          },
          {
            "id": "r07-fin-sheet",
            "type": "output",
            "title": "完成本 Round 小抄",
            "file": "rounds/round_07/final/ai_prep_tool_cheatsheet.md"
          },
          {
            "id": "r07-fin-acc1",
            "type": "test",
            "title": "验收：Round 07 核心目标",
            "file": "round_07.md"
          }
        ]
      }
    ]
  },
  {
    "id": "round_08",
    "title": "Round 08 · 总复盘与升级路线",
    "lane": "engineering",
    "difficulty": "⭐⭐⭐☆☆",
    "duration": "3 周",
    "weeks": [
      {
        "id": "round08-week1",
        "title": "第 1 周：基础练习",
        "tasks": [
          {
            "id": "r08-w1-read",
            "type": "reading",
            "title": "阅读 week1/notes.md",
            "file": "rounds/round_08/week1/notes.md"
          },
          {
            "id": "r08-w1-ex1",
            "type": "exercise",
            "title": "练习1",
            "file": "rounds/round_08/week1/exercises.py"
          },
          {
            "id": "r08-w1-self",
            "type": "test",
            "title": "第1周自测",
            "file": "rounds/round_08/week1/exercises.py"
          }
        ]
      },
      {
        "id": "round08-week2",
        "title": "第 2 周：进阶练习",
        "tasks": [
          {
            "id": "r08-w2-read",
            "type": "reading",
            "title": "阅读 week2/notes.md",
            "file": "rounds/round_08/week2/notes.md"
          },
          {
            "id": "r08-w2-ex2",
            "type": "exercise",
            "title": "练习2",
            "file": "rounds/round_08/week2/exercises.py"
          },
          {
            "id": "r08-w2-self",
            "type": "test",
            "title": "第2周自测",
            "file": "rounds/round_08/week2/exercises.py"
          }
        ]
      },
      {
        "id": "round08-week3",
        "title": "第 3 周：综合练习",
        "tasks": [
          {
            "id": "r08-w3-read",
            "type": "reading",
            "title": "阅读 week3/notes.md",
            "file": "rounds/round_08/week3/notes.md"
          },
          {
            "id": "r08-w3-ex3",
            "type": "exercise",
            "title": "练习3",
            "file": "rounds/round_08/week3/exercises.py"
          },
          {
            "id": "r08-w3-self",
            "type": "test",
            "title": "第3周自测",
            "file": "rounds/round_08/week3/exercises.py"
          }
        ]
      },
      {
        "id": "round08-final",
        "title": "最终验收",
        "tasks": [
          {
            "id": "r08-fin-comp",
            "type": "exercise",
            "title": "综合练习",
            "file": "rounds/round_08/final/comprehensive_exercise.py"
          },
          {
            "id": "r08-fin-sheet",
            "type": "output",
            "title": "完成本 Round 小抄",
            "file": "rounds/round_08/final/upgrade_route_cheatsheet.md"
          },
          {
            "id": "r08-fin-acc1",
            "type": "test",
            "title": "验收：Round 08 核心目标",
            "file": "round_08.md"
          }
        ]
      }
    ]
  },
  {
    "id": "round_09",
    "title": "Round 09 · 仓库规范化与测试入门",
    "lane": "engineering",
    "difficulty": "⭐⭐⭐☆☆",
    "duration": "3 周",
    "weeks": [
      {
        "id": "round09-week1",
        "title": "第 1 周：基础练习",
        "tasks": [
          {
            "id": "r09-w1-read",
            "type": "reading",
            "title": "阅读 week1/notes.md",
            "file": "rounds/round_09/week1/notes.md"
          },
          {
            "id": "r09-w1-ex1",
            "type": "exercise",
            "title": "练习1",
            "file": "rounds/round_09/week1/exercises.py"
          },
          {
            "id": "r09-w1-self",
            "type": "test",
            "title": "第1周自测",
            "file": "rounds/round_09/week1/exercises.py"
          }
        ]
      },
      {
        "id": "round09-week2",
        "title": "第 2 周：进阶练习",
        "tasks": [
          {
            "id": "r09-w2-read",
            "type": "reading",
            "title": "阅读 week2/notes.md",
            "file": "rounds/round_09/week2/notes.md"
          },
          {
            "id": "r09-w2-ex2",
            "type": "exercise",
            "title": "练习2",
            "file": "rounds/round_09/week2/exercises.py"
          },
          {
            "id": "r09-w2-self",
            "type": "test",
            "title": "第2周自测",
            "file": "rounds/round_09/week2/exercises.py"
          }
        ]
      },
      {
        "id": "round09-week3",
        "title": "第 3 周：综合练习",
        "tasks": [
          {
            "id": "r09-w3-read",
            "type": "reading",
            "title": "阅读 week3/notes.md",
            "file": "rounds/round_09/week3/notes.md"
          },
          {
            "id": "r09-w3-ex3",
            "type": "exercise",
            "title": "练习3",
            "file": "rounds/round_09/week3/exercises.py"
          },
          {
            "id": "r09-w3-self",
            "type": "test",
            "title": "第3周自测",
            "file": "rounds/round_09/week3/exercises.py"
          }
        ]
      },
      {
        "id": "round09-final",
        "title": "最终验收",
        "tasks": [
          {
            "id": "r09-fin-comp",
            "type": "exercise",
            "title": "综合练习",
            "file": "rounds/round_09/final/comprehensive_exercise.py"
          },
          {
            "id": "r09-fin-sheet",
            "type": "output",
            "title": "完成本 Round 小抄",
            "file": "rounds/round_09/final/repo_testing_cheatsheet.md"
          },
          {
            "id": "r09-fin-acc1",
            "type": "test",
            "title": "验收：Round 09 核心目标",
            "file": "round_09.md"
          }
        ]
      }
    ]
  },
  {
    "id": "round_10",
    "title": "Round 10 · Python 工程化基础",
    "lane": "engineering",
    "difficulty": "⭐⭐⭐☆☆",
    "duration": "3 周",
    "weeks": [
      {
        "id": "round10-week1",
        "title": "第 1 周：基础练习",
        "tasks": [
          {
            "id": "r10-w1-read",
            "type": "reading",
            "title": "阅读 week1/notes.md",
            "file": "rounds/round_10/week1/notes.md"
          },
          {
            "id": "r10-w1-ex1",
            "type": "exercise",
            "title": "练习1",
            "file": "rounds/round_10/week1/exercises.py"
          },
          {
            "id": "r10-w1-self",
            "type": "test",
            "title": "第1周自测",
            "file": "rounds/round_10/week1/exercises.py"
          }
        ]
      },
      {
        "id": "round10-week2",
        "title": "第 2 周：进阶练习",
        "tasks": [
          {
            "id": "r10-w2-read",
            "type": "reading",
            "title": "阅读 week2/notes.md",
            "file": "rounds/round_10/week2/notes.md"
          },
          {
            "id": "r10-w2-ex2",
            "type": "exercise",
            "title": "练习2",
            "file": "rounds/round_10/week2/exercises.py"
          },
          {
            "id": "r10-w2-self",
            "type": "test",
            "title": "第2周自测",
            "file": "rounds/round_10/week2/exercises.py"
          }
        ]
      },
      {
        "id": "round10-week3",
        "title": "第 3 周：综合练习",
        "tasks": [
          {
            "id": "r10-w3-read",
            "type": "reading",
            "title": "阅读 week3/notes.md",
            "file": "rounds/round_10/week3/notes.md"
          },
          {
            "id": "r10-w3-ex3",
            "type": "exercise",
            "title": "练习3",
            "file": "rounds/round_10/week3/exercises.py"
          },
          {
            "id": "r10-w3-self",
            "type": "test",
            "title": "第3周自测",
            "file": "rounds/round_10/week3/exercises.py"
          }
        ]
      },
      {
        "id": "round10-final",
        "title": "最终验收",
        "tasks": [
          {
            "id": "r10-fin-comp",
            "type": "exercise",
            "title": "综合练习",
            "file": "rounds/round_10/final/comprehensive_exercise.py"
          },
          {
            "id": "r10-fin-sheet",
            "type": "output",
            "title": "完成本 Round 小抄",
            "file": "rounds/round_10/final/python_engineering_cheatsheet.md"
          },
          {
            "id": "r10-fin-acc1",
            "type": "test",
            "title": "验收：Round 10 核心目标",
            "file": "round_10.md"
          }
        ]
      }
    ]
  },
  {
    "id": "round_11",
    "title": "Round 11 · 本地持久化与数据记录",
    "lane": "engineering",
    "difficulty": "⭐⭐⭐☆☆",
    "duration": "3 周",
    "weeks": [
      {
        "id": "round11-week1",
        "title": "第 1 周：基础练习",
        "tasks": [
          {
            "id": "r11-w1-read",
            "type": "reading",
            "title": "阅读 week1/notes.md",
            "file": "rounds/round_11/week1/notes.md"
          },
          {
            "id": "r11-w1-ex1",
            "type": "exercise",
            "title": "练习1",
            "file": "rounds/round_11/week1/exercises.py"
          },
          {
            "id": "r11-w1-self",
            "type": "test",
            "title": "第1周自测",
            "file": "rounds/round_11/week1/exercises.py"
          }
        ]
      },
      {
        "id": "round11-week2",
        "title": "第 2 周：进阶练习",
        "tasks": [
          {
            "id": "r11-w2-read",
            "type": "reading",
            "title": "阅读 week2/notes.md",
            "file": "rounds/round_11/week2/notes.md"
          },
          {
            "id": "r11-w2-ex2",
            "type": "exercise",
            "title": "练习2",
            "file": "rounds/round_11/week2/exercises.py"
          },
          {
            "id": "r11-w2-self",
            "type": "test",
            "title": "第2周自测",
            "file": "rounds/round_11/week2/exercises.py"
          }
        ]
      },
      {
        "id": "round11-week3",
        "title": "第 3 周：综合练习",
        "tasks": [
          {
            "id": "r11-w3-read",
            "type": "reading",
            "title": "阅读 week3/notes.md",
            "file": "rounds/round_11/week3/notes.md"
          },
          {
            "id": "r11-w3-ex3",
            "type": "exercise",
            "title": "练习3",
            "file": "rounds/round_11/week3/exercises.py"
          },
          {
            "id": "r11-w3-self",
            "type": "test",
            "title": "第3周自测",
            "file": "rounds/round_11/week3/exercises.py"
          }
        ]
      },
      {
        "id": "round11-final",
        "title": "最终验收",
        "tasks": [
          {
            "id": "r11-fin-comp",
            "type": "exercise",
            "title": "综合练习",
            "file": "rounds/round_11/final/comprehensive_exercise.py"
          },
          {
            "id": "r11-fin-sheet",
            "type": "output",
            "title": "完成本 Round 小抄",
            "file": "rounds/round_11/final/sqlite_persistence_cheatsheet.md"
          },
          {
            "id": "r11-fin-acc1",
            "type": "test",
            "title": "验收：Round 11 核心目标",
            "file": "round_11.md"
          }
        ]
      }
    ]
  },
  {
    "id": "round_12",
    "title": "Round 12 · 自动化流水线与批处理",
    "lane": "engineering",
    "difficulty": "⭐⭐⭐☆☆",
    "duration": "3 周",
    "weeks": [
      {
        "id": "round12-week1",
        "title": "第 1 周：基础练习",
        "tasks": [
          {
            "id": "r12-w1-read",
            "type": "reading",
            "title": "阅读 week1/notes.md",
            "file": "rounds/round_12/week1/notes.md"
          },
          {
            "id": "r12-w1-ex1",
            "type": "exercise",
            "title": "练习1",
            "file": "rounds/round_12/week1/exercises.py"
          },
          {
            "id": "r12-w1-self",
            "type": "test",
            "title": "第1周自测",
            "file": "rounds/round_12/week1/exercises.py"
          }
        ]
      },
      {
        "id": "round12-week2",
        "title": "第 2 周：进阶练习",
        "tasks": [
          {
            "id": "r12-w2-read",
            "type": "reading",
            "title": "阅读 week2/notes.md",
            "file": "rounds/round_12/week2/notes.md"
          },
          {
            "id": "r12-w2-ex2",
            "type": "exercise",
            "title": "练习2",
            "file": "rounds/round_12/week2/exercises.py"
          },
          {
            "id": "r12-w2-self",
            "type": "test",
            "title": "第2周自测",
            "file": "rounds/round_12/week2/exercises.py"
          }
        ]
      },
      {
        "id": "round12-week3",
        "title": "第 3 周：综合练习",
        "tasks": [
          {
            "id": "r12-w3-read",
            "type": "reading",
            "title": "阅读 week3/notes.md",
            "file": "rounds/round_12/week3/notes.md"
          },
          {
            "id": "r12-w3-ex3",
            "type": "exercise",
            "title": "练习3",
            "file": "rounds/round_12/week3/exercises.py"
          },
          {
            "id": "r12-w3-self",
            "type": "test",
            "title": "第3周自测",
            "file": "rounds/round_12/week3/exercises.py"
          }
        ]
      },
      {
        "id": "round12-final",
        "title": "最终验收",
        "tasks": [
          {
            "id": "r12-fin-comp",
            "type": "exercise",
            "title": "综合练习",
            "file": "rounds/round_12/final/comprehensive_exercise.py"
          },
          {
            "id": "r12-fin-sheet",
            "type": "output",
            "title": "完成本 Round 小抄",
            "file": "rounds/round_12/final/pipeline_automation_cheatsheet.md"
          },
          {
            "id": "r12-fin-acc1",
            "type": "test",
            "title": "验收：Round 12 核心目标",
            "file": "round_12.md"
          }
        ]
      }
    ]
  },
  {
    "id": "round_13",
    "title": "Round 13 · 环境复现与发布基础",
    "lane": "engineering",
    "difficulty": "⭐⭐⭐☆☆",
    "duration": "3 周",
    "weeks": [
      {
        "id": "round13-week1",
        "title": "第 1 周：基础练习",
        "tasks": [
          {
            "id": "r13-w1-read",
            "type": "reading",
            "title": "阅读 week1/notes.md",
            "file": "rounds/round_13/week1/notes.md"
          },
          {
            "id": "r13-w1-ex1",
            "type": "exercise",
            "title": "练习1",
            "file": "rounds/round_13/week1/exercises.py"
          },
          {
            "id": "r13-w1-self",
            "type": "test",
            "title": "第1周自测",
            "file": "rounds/round_13/week1/exercises.py"
          }
        ]
      },
      {
        "id": "round13-week2",
        "title": "第 2 周：进阶练习",
        "tasks": [
          {
            "id": "r13-w2-read",
            "type": "reading",
            "title": "阅读 week2/notes.md",
            "file": "rounds/round_13/week2/notes.md"
          },
          {
            "id": "r13-w2-ex2",
            "type": "exercise",
            "title": "练习2",
            "file": "rounds/round_13/week2/exercises.py"
          },
          {
            "id": "r13-w2-self",
            "type": "test",
            "title": "第2周自测",
            "file": "rounds/round_13/week2/exercises.py"
          }
        ]
      },
      {
        "id": "round13-week3",
        "title": "第 3 周：综合练习",
        "tasks": [
          {
            "id": "r13-w3-read",
            "type": "reading",
            "title": "阅读 week3/notes.md",
            "file": "rounds/round_13/week3/notes.md"
          },
          {
            "id": "r13-w3-ex3",
            "type": "exercise",
            "title": "练习3",
            "file": "rounds/round_13/week3/exercises.py"
          },
          {
            "id": "r13-w3-self",
            "type": "test",
            "title": "第3周自测",
            "file": "rounds/round_13/week3/exercises.py"
          }
        ]
      },
      {
        "id": "round13-final",
        "title": "最终验收",
        "tasks": [
          {
            "id": "r13-fin-comp",
            "type": "exercise",
            "title": "综合练习",
            "file": "rounds/round_13/final/comprehensive_exercise.py"
          },
          {
            "id": "r13-fin-sheet",
            "type": "output",
            "title": "完成本 Round 小抄",
            "file": "rounds/round_13/final/env_repro_cheatsheet.md"
          },
          {
            "id": "r13-fin-acc1",
            "type": "test",
            "title": "验收：Round 13 核心目标",
            "file": "round_13.md"
          }
        ]
      }
    ]
  },
  {
    "id": "round_14",
    "title": "Round 14 · HTTP 与 API 设计基础",
    "lane": "engineering",
    "difficulty": "⭐⭐⭐☆☆",
    "duration": "3 周",
    "weeks": [
      {
        "id": "round14-week1",
        "title": "第 1 周：基础练习",
        "tasks": [
          {
            "id": "r14-w1-read",
            "type": "reading",
            "title": "阅读 week1/notes.md",
            "file": "rounds/round_14/week1/notes.md"
          },
          {
            "id": "r14-w1-ex1",
            "type": "exercise",
            "title": "练习1",
            "file": "rounds/round_14/week1/exercises.py"
          },
          {
            "id": "r14-w1-self",
            "type": "test",
            "title": "第1周自测",
            "file": "rounds/round_14/week1/exercises.py"
          }
        ]
      },
      {
        "id": "round14-week2",
        "title": "第 2 周：进阶练习",
        "tasks": [
          {
            "id": "r14-w2-read",
            "type": "reading",
            "title": "阅读 week2/notes.md",
            "file": "rounds/round_14/week2/notes.md"
          },
          {
            "id": "r14-w2-ex2",
            "type": "exercise",
            "title": "练习2",
            "file": "rounds/round_14/week2/exercises.py"
          },
          {
            "id": "r14-w2-self",
            "type": "test",
            "title": "第2周自测",
            "file": "rounds/round_14/week2/exercises.py"
          }
        ]
      },
      {
        "id": "round14-week3",
        "title": "第 3 周：综合练习",
        "tasks": [
          {
            "id": "r14-w3-read",
            "type": "reading",
            "title": "阅读 week3/notes.md",
            "file": "rounds/round_14/week3/notes.md"
          },
          {
            "id": "r14-w3-ex3",
            "type": "exercise",
            "title": "练习3",
            "file": "rounds/round_14/week3/exercises.py"
          },
          {
            "id": "r14-w3-self",
            "type": "test",
            "title": "第3周自测",
            "file": "rounds/round_14/week3/exercises.py"
          }
        ]
      },
      {
        "id": "round14-final",
        "title": "最终验收",
        "tasks": [
          {
            "id": "r14-fin-comp",
            "type": "exercise",
            "title": "综合练习",
            "file": "rounds/round_14/final/comprehensive_exercise.py"
          },
          {
            "id": "r14-fin-sheet",
            "type": "output",
            "title": "完成本 Round 小抄",
            "file": "rounds/round_14/final/http_api_cheatsheet.md"
          },
          {
            "id": "r14-fin-acc1",
            "type": "test",
            "title": "验收：Round 14 核心目标",
            "file": "round_14.md"
          }
        ]
      }
    ]
  },
  {
    "id": "round_15",
    "title": "Round 15 · FastAPI 基础",
    "lane": "engineering",
    "difficulty": "⭐⭐⭐☆☆",
    "duration": "3 周",
    "weeks": [
      {
        "id": "round15-week1",
        "title": "第 1 周：基础练习",
        "tasks": [
          {
            "id": "r15-w1-read",
            "type": "reading",
            "title": "阅读 week1/notes.md",
            "file": "rounds/round_15/week1/notes.md"
          },
          {
            "id": "r15-w1-ex1",
            "type": "exercise",
            "title": "练习1",
            "file": "rounds/round_15/week1/exercises.py"
          },
          {
            "id": "r15-w1-self",
            "type": "test",
            "title": "第1周自测",
            "file": "rounds/round_15/week1/exercises.py"
          }
        ]
      },
      {
        "id": "round15-week2",
        "title": "第 2 周：进阶练习",
        "tasks": [
          {
            "id": "r15-w2-read",
            "type": "reading",
            "title": "阅读 week2/notes.md",
            "file": "rounds/round_15/week2/notes.md"
          },
          {
            "id": "r15-w2-ex2",
            "type": "exercise",
            "title": "练习2",
            "file": "rounds/round_15/week2/exercises.py"
          },
          {
            "id": "r15-w2-self",
            "type": "test",
            "title": "第2周自测",
            "file": "rounds/round_15/week2/exercises.py"
          }
        ]
      },
      {
        "id": "round15-week3",
        "title": "第 3 周：综合练习",
        "tasks": [
          {
            "id": "r15-w3-read",
            "type": "reading",
            "title": "阅读 week3/notes.md",
            "file": "rounds/round_15/week3/notes.md"
          },
          {
            "id": "r15-w3-ex3",
            "type": "exercise",
            "title": "练习3",
            "file": "rounds/round_15/week3/exercises.py"
          },
          {
            "id": "r15-w3-self",
            "type": "test",
            "title": "第3周自测",
            "file": "rounds/round_15/week3/exercises.py"
          }
        ]
      },
      {
        "id": "round15-final",
        "title": "最终验收",
        "tasks": [
          {
            "id": "r15-fin-comp",
            "type": "exercise",
            "title": "综合练习",
            "file": "rounds/round_15/final/comprehensive_exercise.py"
          },
          {
            "id": "r15-fin-sheet",
            "type": "output",
            "title": "完成本 Round 小抄",
            "file": "rounds/round_15/final/fastapi_basics_cheatsheet.md"
          },
          {
            "id": "r15-fin-acc1",
            "type": "test",
            "title": "验收：Round 15 核心目标",
            "file": "round_15.md"
          }
        ]
      }
    ]
  },
  {
    "id": "round_16",
    "title": "Round 16 · API 与数据层结合",
    "lane": "engineering",
    "difficulty": "⭐⭐⭐☆☆",
    "duration": "3 周",
    "weeks": [
      {
        "id": "round16-week1",
        "title": "第 1 周：基础练习",
        "tasks": [
          {
            "id": "r16-w1-read",
            "type": "reading",
            "title": "阅读 week1/notes.md",
            "file": "rounds/round_16/week1/notes.md"
          },
          {
            "id": "r16-w1-ex1",
            "type": "exercise",
            "title": "练习1",
            "file": "rounds/round_16/week1/exercises.py"
          },
          {
            "id": "r16-w1-self",
            "type": "test",
            "title": "第1周自测",
            "file": "rounds/round_16/week1/exercises.py"
          }
        ]
      },
      {
        "id": "round16-week2",
        "title": "第 2 周：进阶练习",
        "tasks": [
          {
            "id": "r16-w2-read",
            "type": "reading",
            "title": "阅读 week2/notes.md",
            "file": "rounds/round_16/week2/notes.md"
          },
          {
            "id": "r16-w2-ex2",
            "type": "exercise",
            "title": "练习2",
            "file": "rounds/round_16/week2/exercises.py"
          },
          {
            "id": "r16-w2-self",
            "type": "test",
            "title": "第2周自测",
            "file": "rounds/round_16/week2/exercises.py"
          }
        ]
      },
      {
        "id": "round16-week3",
        "title": "第 3 周：综合练习",
        "tasks": [
          {
            "id": "r16-w3-read",
            "type": "reading",
            "title": "阅读 week3/notes.md",
            "file": "rounds/round_16/week3/notes.md"
          },
          {
            "id": "r16-w3-ex3",
            "type": "exercise",
            "title": "练习3",
            "file": "rounds/round_16/week3/exercises.py"
          },
          {
            "id": "r16-w3-self",
            "type": "test",
            "title": "第3周自测",
            "file": "rounds/round_16/week3/exercises.py"
          }
        ]
      },
      {
        "id": "round16-final",
        "title": "最终验收",
        "tasks": [
          {
            "id": "r16-fin-comp",
            "type": "exercise",
            "title": "综合练习",
            "file": "rounds/round_16/final/comprehensive_exercise.py"
          },
          {
            "id": "r16-fin-sheet",
            "type": "output",
            "title": "完成本 Round 小抄",
            "file": "rounds/round_16/final/api_data_layer_cheatsheet.md"
          },
          {
            "id": "r16-fin-acc1",
            "type": "test",
            "title": "验收：Round 16 核心目标",
            "file": "round_16.md"
          }
        ]
      }
    ]
  },
  {
    "id": "round_17",
    "title": "Round 17 · 服务化收口",
    "lane": "engineering",
    "difficulty": "⭐⭐⭐☆☆",
    "duration": "3 周",
    "weeks": [
      {
        "id": "round17-week1",
        "title": "第 1 周：基础练习",
        "tasks": [
          {
            "id": "r17-w1-read",
            "type": "reading",
            "title": "阅读 week1/notes.md",
            "file": "rounds/round_17/week1/notes.md"
          },
          {
            "id": "r17-w1-ex1",
            "type": "exercise",
            "title": "练习1",
            "file": "rounds/round_17/week1/exercises.py"
          },
          {
            "id": "r17-w1-self",
            "type": "test",
            "title": "第1周自测",
            "file": "rounds/round_17/week1/exercises.py"
          }
        ]
      },
      {
        "id": "round17-week2",
        "title": "第 2 周：进阶练习",
        "tasks": [
          {
            "id": "r17-w2-read",
            "type": "reading",
            "title": "阅读 week2/notes.md",
            "file": "rounds/round_17/week2/notes.md"
          },
          {
            "id": "r17-w2-ex2",
            "type": "exercise",
            "title": "练习2",
            "file": "rounds/round_17/week2/exercises.py"
          },
          {
            "id": "r17-w2-self",
            "type": "test",
            "title": "第2周自测",
            "file": "rounds/round_17/week2/exercises.py"
          }
        ]
      },
      {
        "id": "round17-week3",
        "title": "第 3 周：综合练习",
        "tasks": [
          {
            "id": "r17-w3-read",
            "type": "reading",
            "title": "阅读 week3/notes.md",
            "file": "rounds/round_17/week3/notes.md"
          },
          {
            "id": "r17-w3-ex3",
            "type": "exercise",
            "title": "练习3",
            "file": "rounds/round_17/week3/exercises.py"
          },
          {
            "id": "r17-w3-self",
            "type": "test",
            "title": "第3周自测",
            "file": "rounds/round_17/week3/exercises.py"
          }
        ]
      },
      {
        "id": "round17-final",
        "title": "最终验收",
        "tasks": [
          {
            "id": "r17-fin-comp",
            "type": "exercise",
            "title": "综合练习",
            "file": "rounds/round_17/final/comprehensive_exercise.py"
          },
          {
            "id": "r17-fin-sheet",
            "type": "output",
            "title": "完成本 Round 小抄",
            "file": "rounds/round_17/final/service_wrapup_cheatsheet.md"
          },
          {
            "id": "r17-fin-acc1",
            "type": "test",
            "title": "验收：Round 17 核心目标",
            "file": "round_17.md"
          }
        ]
      }
    ]
  },
  {
    "id": "round_18",
    "title": "Round 18 · 数值计算与数据分析前置",
    "lane": "engineering",
    "difficulty": "⭐⭐⭐☆☆",
    "duration": "3 周",
    "weeks": [
      {
        "id": "round18-week1",
        "title": "第 1 周：基础练习",
        "tasks": [
          {
            "id": "r18-w1-read",
            "type": "reading",
            "title": "阅读 week1/notes.md",
            "file": "rounds/round_18/week1/notes.md"
          },
          {
            "id": "r18-w1-ex1",
            "type": "exercise",
            "title": "练习1",
            "file": "rounds/round_18/week1/exercises.py"
          },
          {
            "id": "r18-w1-self",
            "type": "test",
            "title": "第1周自测",
            "file": "rounds/round_18/week1/exercises.py"
          }
        ]
      },
      {
        "id": "round18-week2",
        "title": "第 2 周：进阶练习",
        "tasks": [
          {
            "id": "r18-w2-read",
            "type": "reading",
            "title": "阅读 week2/notes.md",
            "file": "rounds/round_18/week2/notes.md"
          },
          {
            "id": "r18-w2-ex2",
            "type": "exercise",
            "title": "练习2",
            "file": "rounds/round_18/week2/exercises.py"
          },
          {
            "id": "r18-w2-self",
            "type": "test",
            "title": "第2周自测",
            "file": "rounds/round_18/week2/exercises.py"
          }
        ]
      },
      {
        "id": "round18-week3",
        "title": "第 3 周：综合练习",
        "tasks": [
          {
            "id": "r18-w3-read",
            "type": "reading",
            "title": "阅读 week3/notes.md",
            "file": "rounds/round_18/week3/notes.md"
          },
          {
            "id": "r18-w3-ex3",
            "type": "exercise",
            "title": "练习3",
            "file": "rounds/round_18/week3/exercises.py"
          },
          {
            "id": "r18-w3-self",
            "type": "test",
            "title": "第3周自测",
            "file": "rounds/round_18/week3/exercises.py"
          }
        ]
      },
      {
        "id": "round18-final",
        "title": "最终验收",
        "tasks": [
          {
            "id": "r18-fin-comp",
            "type": "exercise",
            "title": "综合练习",
            "file": "rounds/round_18/final/comprehensive_exercise.py"
          },
          {
            "id": "r18-fin-sheet",
            "type": "output",
            "title": "完成本 Round 小抄",
            "file": "rounds/round_18/final/numerics_analytics_cheatsheet.md"
          },
          {
            "id": "r18-fin-acc1",
            "type": "test",
            "title": "验收：Round 18 核心目标",
            "file": "round_18.md"
          }
        ]
      }
    ]
  },
  {
    "id": "round_19",
    "title": "Round 19 · 机器学习最小闭环",
    "lane": "engineering",
    "difficulty": "⭐⭐⭐☆☆",
    "duration": "3 周",
    "weeks": [
      {
        "id": "round19-week1",
        "title": "第 1 周：基础练习",
        "tasks": [
          {
            "id": "r19-w1-read",
            "type": "reading",
            "title": "阅读 week1/notes.md",
            "file": "rounds/round_19/week1/notes.md"
          },
          {
            "id": "r19-w1-ex1",
            "type": "exercise",
            "title": "练习1",
            "file": "rounds/round_19/week1/exercises.py"
          },
          {
            "id": "r19-w1-self",
            "type": "test",
            "title": "第1周自测",
            "file": "rounds/round_19/week1/exercises.py"
          }
        ]
      },
      {
        "id": "round19-week2",
        "title": "第 2 周：进阶练习",
        "tasks": [
          {
            "id": "r19-w2-read",
            "type": "reading",
            "title": "阅读 week2/notes.md",
            "file": "rounds/round_19/week2/notes.md"
          },
          {
            "id": "r19-w2-ex2",
            "type": "exercise",
            "title": "练习2",
            "file": "rounds/round_19/week2/exercises.py"
          },
          {
            "id": "r19-w2-self",
            "type": "test",
            "title": "第2周自测",
            "file": "rounds/round_19/week2/exercises.py"
          }
        ]
      },
      {
        "id": "round19-week3",
        "title": "第 3 周：综合练习",
        "tasks": [
          {
            "id": "r19-w3-read",
            "type": "reading",
            "title": "阅读 week3/notes.md",
            "file": "rounds/round_19/week3/notes.md"
          },
          {
            "id": "r19-w3-ex3",
            "type": "exercise",
            "title": "练习3",
            "file": "rounds/round_19/week3/exercises.py"
          },
          {
            "id": "r19-w3-self",
            "type": "test",
            "title": "第3周自测",
            "file": "rounds/round_19/week3/exercises.py"
          }
        ]
      },
      {
        "id": "round19-final",
        "title": "最终验收",
        "tasks": [
          {
            "id": "r19-fin-comp",
            "type": "exercise",
            "title": "综合练习",
            "file": "rounds/round_19/final/comprehensive_exercise.py"
          },
          {
            "id": "r19-fin-sheet",
            "type": "output",
            "title": "完成本 Round 小抄",
            "file": "rounds/round_19/final/ml_minimal_loop_cheatsheet.md"
          },
          {
            "id": "r19-fin-acc1",
            "type": "test",
            "title": "验收：Round 19 核心目标",
            "file": "round_19.md"
          }
        ]
      }
    ]
  },
  {
    "id": "round_20",
    "title": "Round 20 · PyTorch 入门",
    "lane": "engineering",
    "difficulty": "⭐⭐⭐☆☆",
    "duration": "3 周",
    "weeks": [
      {
        "id": "round20-week1",
        "title": "第 1 周：基础练习",
        "tasks": [
          {
            "id": "r20-w1-read",
            "type": "reading",
            "title": "阅读 week1/notes.md",
            "file": "rounds/round_20/week1/notes.md"
          },
          {
            "id": "r20-w1-ex1",
            "type": "exercise",
            "title": "练习1",
            "file": "rounds/round_20/week1/exercises.py"
          },
          {
            "id": "r20-w1-self",
            "type": "test",
            "title": "第1周自测",
            "file": "rounds/round_20/week1/exercises.py"
          }
        ]
      },
      {
        "id": "round20-week2",
        "title": "第 2 周：进阶练习",
        "tasks": [
          {
            "id": "r20-w2-read",
            "type": "reading",
            "title": "阅读 week2/notes.md",
            "file": "rounds/round_20/week2/notes.md"
          },
          {
            "id": "r20-w2-ex2",
            "type": "exercise",
            "title": "练习2",
            "file": "rounds/round_20/week2/exercises.py"
          },
          {
            "id": "r20-w2-self",
            "type": "test",
            "title": "第2周自测",
            "file": "rounds/round_20/week2/exercises.py"
          }
        ]
      },
      {
        "id": "round20-week3",
        "title": "第 3 周：综合练习",
        "tasks": [
          {
            "id": "r20-w3-read",
            "type": "reading",
            "title": "阅读 week3/notes.md",
            "file": "rounds/round_20/week3/notes.md"
          },
          {
            "id": "r20-w3-ex3",
            "type": "exercise",
            "title": "练习3",
            "file": "rounds/round_20/week3/exercises.py"
          },
          {
            "id": "r20-w3-self",
            "type": "test",
            "title": "第3周自测",
            "file": "rounds/round_20/week3/exercises.py"
          }
        ]
      },
      {
        "id": "round20-final",
        "title": "最终验收",
        "tasks": [
          {
            "id": "r20-fin-comp",
            "type": "exercise",
            "title": "综合练习",
            "file": "rounds/round_20/final/comprehensive_exercise.py"
          },
          {
            "id": "r20-fin-sheet",
            "type": "output",
            "title": "完成本 Round 小抄",
            "file": "rounds/round_20/final/pytorch_intro_cheatsheet.md"
          },
          {
            "id": "r20-fin-acc1",
            "type": "test",
            "title": "验收：Round 20 核心目标",
            "file": "round_20.md"
          }
        ]
      }
    ]
  },
  {
    "id": "round_21",
    "title": "Round 21 · NLP 前置基础",
    "lane": "engineering",
    "difficulty": "⭐⭐⭐☆☆",
    "duration": "3 周",
    "weeks": [
      {
        "id": "round21-week1",
        "title": "第 1 周：基础练习",
        "tasks": [
          {
            "id": "r21-w1-read",
            "type": "reading",
            "title": "阅读 week1/notes.md",
            "file": "rounds/round_21/week1/notes.md"
          },
          {
            "id": "r21-w1-ex1",
            "type": "exercise",
            "title": "练习1",
            "file": "rounds/round_21/week1/exercises.py"
          },
          {
            "id": "r21-w1-self",
            "type": "test",
            "title": "第1周自测",
            "file": "rounds/round_21/week1/exercises.py"
          }
        ]
      },
      {
        "id": "round21-week2",
        "title": "第 2 周：进阶练习",
        "tasks": [
          {
            "id": "r21-w2-read",
            "type": "reading",
            "title": "阅读 week2/notes.md",
            "file": "rounds/round_21/week2/notes.md"
          },
          {
            "id": "r21-w2-ex2",
            "type": "exercise",
            "title": "练习2",
            "file": "rounds/round_21/week2/exercises.py"
          },
          {
            "id": "r21-w2-self",
            "type": "test",
            "title": "第2周自测",
            "file": "rounds/round_21/week2/exercises.py"
          }
        ]
      },
      {
        "id": "round21-week3",
        "title": "第 3 周：综合练习",
        "tasks": [
          {
            "id": "r21-w3-read",
            "type": "reading",
            "title": "阅读 week3/notes.md",
            "file": "rounds/round_21/week3/notes.md"
          },
          {
            "id": "r21-w3-ex3",
            "type": "exercise",
            "title": "练习3",
            "file": "rounds/round_21/week3/exercises.py"
          },
          {
            "id": "r21-w3-self",
            "type": "test",
            "title": "第3周自测",
            "file": "rounds/round_21/week3/exercises.py"
          }
        ]
      },
      {
        "id": "round21-final",
        "title": "最终验收",
        "tasks": [
          {
            "id": "r21-fin-comp",
            "type": "exercise",
            "title": "综合练习",
            "file": "rounds/round_21/final/comprehensive_exercise.py"
          },
          {
            "id": "r21-fin-sheet",
            "type": "output",
            "title": "完成本 Round 小抄",
            "file": "rounds/round_21/final/nlp_prereq_cheatsheet.md"
          },
          {
            "id": "r21-fin-acc1",
            "type": "test",
            "title": "验收：Round 21 核心目标",
            "file": "round_21.md"
          }
        ]
      }
    ]
  },
  {
    "id": "plan_soft_exam",
    "title": "软考 · 启动模块",
    "lane": "soft_exam",
    "difficulty": "⭐☆☆☆☆",
    "duration": "持续",
    "weeks": [
      {
        "id": "plan_soft_exam_week",
        "title": "计划文档阅读",
        "tasks": [
          {
            "id": "soft_exam-ds-start",
            "type": "reading",
            "title": "阅读软考数据结构骨架",
            "file": "plans/soft_exam/ds.md"
          },
          {
            "id": "soft_exam-os-start",
            "type": "reading",
            "title": "阅读软考操作系统骨架",
            "file": "plans/soft_exam/os.md"
          },
          {
            "id": "soft_exam-db-start",
            "type": "reading",
            "title": "阅读软考数据库骨架",
            "file": "plans/soft_exam/db.md"
          }
        ]
      }
    ]
  },
  {
    "id": "plan_math2",
    "title": "数学二 · 启动模块",
    "lane": "math2",
    "difficulty": "⭐☆☆☆☆",
    "duration": "持续",
    "weeks": [
      {
        "id": "plan_math2_week",
        "title": "计划文档阅读",
        "tasks": [
          {
            "id": "math2-limits-start",
            "type": "reading",
            "title": "阅读数学二极限启动骨架",
            "file": "plans/math2/limits.md"
          },
          {
            "id": "math2-la-start",
            "type": "reading",
            "title": "阅读数学二线性代数启动骨架",
            "file": "plans/math2/la_matrix.md"
          }
        ]
      }
    ]
  },
  {
    "id": "plan_cs408",
    "title": "408 · 启动模块",
    "lane": "cs408",
    "difficulty": "⭐☆☆☆☆",
    "duration": "持续",
    "weeks": [
      {
        "id": "plan_cs408_week",
        "title": "计划文档阅读",
        "tasks": [
          {
            "id": "cs408-ds-start",
            "type": "reading",
            "title": "阅读 408 数据结构计划入口",
            "file": "plans/408/README.md"
          }
        ]
      }
    ]
  }
];
