#!/usr/bin/env python3
"""Round 15 · Week 2: generate request-body and Pydantic model skeletons."""

from __future__ import annotations

import ast
import json
import shutil
import subprocess
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[3]
LAB = Path.home() / "cli-lab" / "round15" / "week2_auto" / "pydantic_body"

SCHEMAS_PY = '''"""Pydantic schemas generated by Round 15 Week 2."""

from pydantic import BaseModel, Field


class RunRequest(BaseModel):
    input_file: str = Field(..., description="Input file path", examples=["input/labels.txt"])
    format: str = Field("txt", description="Input file format", examples=["txt"])
    dedup: bool = Field(False, description="Whether to remove duplicated rows")


class RunResponse(BaseModel):
    run_id: int
    status: str
    input_file: str
    processed_count: int | None = None
    message: str | None = None


class RunRecord(BaseModel):
    id: int
    input_file: str
    output_file: str | None = None
    format: str
    original_count: int
    processed_count: int
    dedup: bool
    run_time: str
'''

MAIN_PY = '''"""POST /run example generated by Round 15 Week 2."""

from fastapi import FastAPI
from app.schemas import RunRequest, RunResponse

app = FastAPI(title="AI Prep Tool API", version="0.1.0")


@app.post("/run", response_model=RunResponse, tags=["jobs"])
def trigger_run(req: RunRequest) -> RunResponse:
    """Submit one data-processing run."""
    return RunResponse(
        run_id=1001,
        status="completed",
        input_file=req.input_file,
        processed_count=3,
        message=f"Processed {req.input_file} with format={req.format}, dedup={req.dedup}",
    )
'''

MODEL_CHECK = '''#!/usr/bin/env python3
"""Static checks for Round 15 Week 2 generated Pydantic skeletons."""

import ast
import json
from pathlib import Path

base = Path(__file__).resolve().parent
schemas_source = (base / "app" / "schemas.py").read_text(encoding="utf-8")
main_source = (base / "app" / "main.py").read_text(encoding="utf-8")
schemas_tree = ast.parse(schemas_source)
class_names = {node.name for node in ast.walk(schemas_tree) if isinstance(node, ast.ClassDef)}
field_names = {}
for node in ast.walk(schemas_tree):
    if isinstance(node, ast.ClassDef):
        field_names[node.name] = [stmt.target.id for stmt in node.body if isinstance(stmt, ast.AnnAssign) and isinstance(stmt.target, ast.Name)]

checks = {
    "models_exist": {"RunRequest", "RunResponse", "RunRecord"}.issubset(class_names),
    "request_fields": {"input_file", "format", "dedup"}.issubset(set(field_names.get("RunRequest", []))),
    "response_fields": {"run_id", "status", "input_file"}.issubset(set(field_names.get("RunResponse", []))),
    "post_route": '@app.post("/run", response_model=RunResponse' in main_source,
    "request_body_param": "req: RunRequest" in main_source,
    "returns_response_model": "-> RunResponse" in main_source,
}
report = {"ok": all(checks.values()), "checks": checks, "fields": field_names}
(base / "model_check_report.json").write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\\n", encoding="utf-8")
print(json.dumps(report, ensure_ascii=False, sort_keys=True))
raise SystemExit(0 if report["ok"] else 1)
'''


def mark(task_id: str) -> None:
    subprocess.run(["bash", str(REPO_ROOT / "mark_done.sh"), task_id], cwd=REPO_ROOT, check=True)


def reset_lab() -> None:
    if LAB.exists():
        shutil.rmtree(LAB)
    (LAB / "app").mkdir(parents=True)
    (LAB / "samples").mkdir()


def main() -> None:
    reset_lab()
    (LAB / "app" / "__init__.py").write_text("", encoding="utf-8")
    (LAB / "app" / "schemas.py").write_text(SCHEMAS_PY, encoding="utf-8")
    (LAB / "app" / "main.py").write_text(MAIN_PY, encoding="utf-8")
    (LAB / "samples" / "request_run.json").write_text(
        json.dumps({"input_file": "input/labels.txt", "format": "txt", "dedup": True}, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    (LAB / "samples" / "response_run.json").write_text(
        json.dumps({"run_id": 1001, "status": "completed", "input_file": "input/labels.txt", "processed_count": 3}, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    check = LAB / "model_check.py"
    check.write_text(MODEL_CHECK, encoding="utf-8")
    check.chmod(0o755)
    proc = subprocess.run(["python3", str(check)], cwd=LAB, capture_output=True, text=True, check=False)
    if proc.returncode != 0:
        raise RuntimeError(proc.stderr or proc.stdout)
    print("Round 15 Week 2 请求体与 Pydantic 模型")
    print("sandbox:", LAB)
    print("model_count:", 3)
    print("report:", LAB / "model_check_report.json")
    mark("r15-w2-ex2")


if __name__ == "__main__":
    main()
