#!/usr/bin/env python3
"""Round 15 · Week 1: generate a FastAPI read-interface skeleton."""

from __future__ import annotations

import json
import shutil
import subprocess
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[3]
LAB = Path.home() / "cli-lab" / "round15" / "week1_auto" / "fastapi_entry"

MAIN_PY = '''"""FastAPI entrypoint generated by Round 15 Week 1."""

from fastapi import FastAPI, HTTPException

app = FastAPI(
    title="AI Prep Tool API",
    version="0.1.0",
    description="Round 15 Week 1 read interfaces.",
)

FAKE_RUNS = {
    1: {"id": 1, "input_file": "input/demo.txt", "format": "txt", "processed_count": 3},
    2: {"id": 2, "input_file": "input/labels.csv", "format": "csv", "processed_count": 42},
}


@app.get("/health", tags=["system"])
def health() -> dict[str, str]:
    """Return a minimal health signal."""
    return {"status": "ok", "service": "ai_prep_tool_api"}


@app.get("/runs/{run_id}", tags=["runs"])
def get_run(run_id: int) -> dict:
    """Get one run by integer path parameter."""
    if run_id not in FAKE_RUNS:
        raise HTTPException(status_code=404, detail=f"Run {run_id} not found")
    return FAKE_RUNS[run_id]


@app.get("/runs", tags=["runs"])
def list_runs(skip: int = 0, limit: int = 20, format: str | None = None) -> dict:
    """List runs with query parameters."""
    limit = min(max(limit, 1), 100)
    runs = list(FAKE_RUNS.values())
    if format:
        runs = [item for item in runs if item.get("format") == format]
    return {"runs": runs[skip: skip + limit], "total": len(runs), "skip": skip, "limit": limit}
'''

STATIC_CHECK = '''#!/usr/bin/env python3
"""Static checks for the generated FastAPI entrypoint."""

import ast
import json
from pathlib import Path

base = Path(__file__).resolve().parent
source = (base / "app" / "main.py").read_text(encoding="utf-8")
tree = ast.parse(source)
decorators = []
for node in ast.walk(tree):
    if isinstance(node, ast.FunctionDef):
        for deco in node.decorator_list:
            if isinstance(deco, ast.Call) and isinstance(deco.func, ast.Attribute):
                path = deco.args[0].value if deco.args and isinstance(deco.args[0], ast.Constant) else ""
                decorators.append({"function": node.name, "method": deco.func.attr.upper(), "path": path})

checks = {
    "fastapi_app": "app = FastAPI(" in source,
    "health_route": {"method": "GET", "path": "/health", "function": "health"} in decorators,
    "run_detail_route": {"method": "GET", "path": "/runs/{run_id}", "function": "get_run"} in decorators,
    "run_list_route": {"method": "GET", "path": "/runs", "function": "list_runs"} in decorators,
    "path_parameter_type": "run_id: int" in source,
    "query_defaults": "skip: int = 0" in source and "limit: int = 20" in source,
    "not_found_error": "HTTPException(status_code=404" in source,
}
report = {"ok": all(checks.values()), "checks": checks, "routes": decorators}
(base / "static_check_report.json").write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\\n", encoding="utf-8")
print(json.dumps(report, ensure_ascii=False, sort_keys=True))
raise SystemExit(0 if report["ok"] else 1)
'''


def mark(task_id: str) -> None:
    subprocess.run(["bash", str(REPO_ROOT / "mark_done.sh"), task_id], cwd=REPO_ROOT, check=True)


def reset_lab() -> None:
    if LAB.exists():
        shutil.rmtree(LAB)
    (LAB / "app").mkdir(parents=True)


def main() -> None:
    reset_lab()
    (LAB / "app" / "__init__.py").write_text("", encoding="utf-8")
    (LAB / "app" / "main.py").write_text(MAIN_PY, encoding="utf-8")
    (LAB / "route_table.json").write_text(
        json.dumps(
            [
                {"method": "GET", "path": "/health", "parameter_source": "none", "success_status": 200},
                {"method": "GET", "path": "/runs/{run_id}", "parameter_source": "path", "success_status": 200, "error_status": 404},
                {"method": "GET", "path": "/runs", "parameter_source": "query", "success_status": 200},
            ],
            ensure_ascii=False,
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    check = LAB / "static_check.py"
    check.write_text(STATIC_CHECK, encoding="utf-8")
    check.chmod(0o755)
    proc = subprocess.run(["python3", str(check)], cwd=LAB, capture_output=True, text=True, check=False)
    if proc.returncode != 0:
        raise RuntimeError(proc.stderr or proc.stdout)
    (LAB / "next_steps.txt").write_text(
        "1. Read app/main.py and explain app/route/function.\n"
        "2. Explain why run_id is a path parameter.\n"
        "3. Explain why skip and limit are query parameters.\n",
        encoding="utf-8",
    )
    print("Round 15 Week 1 FastAPI 应用入口")
    print("sandbox:", LAB)
    print("route_count:", 3)
    print("report:", LAB / "static_check_report.json")
    mark("r15-w1-ex1")


if __name__ == "__main__":
    main()
