#!/usr/bin/env python3
"""Sync progress_rounds.json + progress_rounds.js from repo state.

- Keeps detailed weeks/tasks for rounds already in progress_rounds.json.
- Adds scaffold-only entries for rounds with dirs but no progress tasks.
- Agents should run this after expanding a round or linking progress tasks.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
JSON_PATH = REPO / "progress_rounds.json"
JS_PATH = REPO / "progress_rounds.js"

# Import scan helpers from sibling module
sys.path.insert(0, str(REPO / "scripts"))
from round_status import scan_rounds, tier_label  # noqa: E402


def load_existing() -> dict:
    if not JSON_PATH.is_file():
        return {"version": 1, "rounds": []}
    return json.loads(JSON_PATH.read_text(encoding="utf-8"))


def scaffold_round_entry(st) -> dict:
    return {
        "id": st.round_id,
        "title": st.title,
        "lane": st.lanes[0],
        "lanes": st.lanes,
        "difficulty": st.difficulty or "—",
        "duration": "3 周",
        "tier": tier_label(st),
        "progress_linked": st.progress_linked,
        "scaffold_only": not st.progress_linked,
        "readme": f"rounds/{st.round_id}/README.md",
        "weeks": [],
    }


def sync_rounds() -> dict:
    existing = load_existing()
    by_id = {r["id"]: r for r in existing.get("rounds", []) if r.get("id")}
    statuses = scan_rounds(REPO)

    merged: list[dict] = []
    for st in statuses:
        if st.round_id in by_id and by_id[st.round_id].get("weeks"):
            entry = dict(by_id[st.round_id])
        elif st.progress_linked and st.round_id in by_id:
            entry = dict(by_id[st.round_id])
        elif st.scaffold_dir or st.overview_md:
            entry = scaffold_round_entry(st)
        else:
            continue

        entry["tier"] = tier_label(st)
        entry["progress_linked"] = st.progress_linked
        entry["scaffold_only"] = not st.progress_linked
        entry.setdefault("lanes", st.lanes)
        merged.append(entry)

    payload = {
        "version": 1,
        "generated_note": "由 scripts/generate_progress_rounds.py 维护；勿手工编造轮次列表。",
        "rounds": merged,
    }
    return payload


def write_js(payload: dict) -> None:
    body = json.dumps(payload, ensure_ascii=False, indent=2)
    JS_PATH.write_text(
        "// Auto-generated by scripts/generate_progress_rounds.py — DO NOT edit manually\n"
        f"window.PROGRESS_ROUNDS = {body};\n",
        encoding="utf-8",
    )


def main() -> int:
    payload = sync_rounds()
    JSON_PATH.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    write_js(payload)
    linked = [r["id"] for r in payload["rounds"] if r.get("progress_linked")]
    scaffold = [r["id"] for r in payload["rounds"] if r.get("scaffold_only")]
    print(f"progress_rounds: {len(payload['rounds'])} rounds "
          f"({len(linked)} progress-linked, {len(scaffold)} scaffold-only)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
