#!/usr/bin/env python3
"""Single write path for progress.json, progress_data.js, and action events."""

from __future__ import annotations

import argparse
import datetime
import json
import re
import sys
import uuid
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent

DEFAULT_LANES: dict[str, dict[str, str]] = {
    "engineering": {
        "title": "工程实操线",
        "description": "Linux/Shell/Git/Python/工程化/服务化/AI 工程/VPS",
    },
    "soft_exam": {
        "title": "软考中级线",
        "description": "默认软件设计师，高分/满分导向",
    },
    "math2": {
        "title": "数学二线",
        "description": "高等数学 + 线性代数（长期低强度）",
    },
    "cs408": {
        "title": "408/0854 线",
        "description": "数据结构 + 计组 + 操作系统 + 计算机网络",
    },
}

ALLOWED_RESULTS = frozenset({"ok", "noop_already_done"})


def repo_root() -> Path:
    return REPO_ROOT


def progress_json_path(root: Path | None = None) -> Path:
    return (root or REPO_ROOT) / "progress.json"


def progress_js_path(root: Path | None = None) -> Path:
    return (root or REPO_ROOT) / "progress_data.js"


def action_log_path(root: Path | None = None) -> Path:
    return (root or REPO_ROOT) / "records" / "action_logs" / "events.jsonl"


def resolve_round_id(task_id: str) -> str:
    if task_id.startswith(("w1-", "w2-", "w3-", "fin-")):
        return "round_00"
    match = re.match(r"^r(\d+)-", task_id)
    if match:
        return f"round_{int(match.group(1)):02d}"
    return "unknown"


def normalize_progress(data: dict[str, Any]) -> dict[str, Any]:
    data["version"] = 2
    if "lanes" not in data:
        data["lanes"] = dict(DEFAULT_LANES)
    else:
        for key, meta in DEFAULT_LANES.items():
            data["lanes"].setdefault(key, dict(meta))
    tasks = data.setdefault("tasks", {})
    for info in tasks.values():
        if isinstance(info, dict) and "lane" not in info:
            info["lane"] = "engineering"
    return data


def load_progress(root: Path | None = None) -> dict[str, Any]:
    path = progress_json_path(root)
    with path.open("r", encoding="utf-8") as f:
        data = json.load(f)
    return normalize_progress(data)


def write_progress_data_js(data: dict[str, Any], root: Path | None = None) -> None:
    js_path = progress_js_path(root)
    payload = {
        "version": data.get("version", 2),
        "lanes": data.get("lanes", {}),
        "tasks": data.get("tasks", {}),
    }
    body = json.dumps(payload, ensure_ascii=False, indent=2)
    content = (
        "// Auto-generated by progress_store.py — DO NOT edit manually\n"
        "// Source of truth: progress.json\n"
        f"window.PROGRESS_DATA = {body};\n"
    )
    js_path.write_text(content, encoding="utf-8")


def save_progress(data: dict[str, Any], root: Path | None = None) -> None:
    path = progress_json_path(root)
    with path.open("w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    write_progress_data_js(data, root)


def append_event(
    task_id: str,
    lane: str,
    action_type: str,
    result: str,
    root: Path | None = None,
) -> dict[str, Any]:
    event = {
        "action_id": str(uuid.uuid4()),
        "task_id": task_id,
        "round_id": resolve_round_id(task_id),
        "lane": lane,
        "action_type": action_type,
        "timestamp": datetime.datetime.now().isoformat(timespec="seconds"),
        "result": result,
        "note": "",
        "evidence_path": "",
    }
    log_path = action_log_path(root)
    log_path.parent.mkdir(parents=True, exist_ok=True)
    with log_path.open("a", encoding="utf-8") as f:
        f.write(json.dumps(event, ensure_ascii=False) + "\n")
    return event


def set_task_done(task_id: str, undo: bool = False, root: Path | None = None) -> dict[str, Any]:
    data = load_progress(root)
    tasks = data["tasks"]
    if task_id not in tasks:
        raise KeyError(f"unknown task_id: {task_id}")

    task = tasks[task_id]
    action_type = "undo_done" if undo else "mark_done"
    result = "ok"
    message = ""

    if undo:
        task["done"] = False
        task["done_at"] = None
        message = f"↩️  已取消完成：{task_id}"
    elif task.get("done"):
        result = "noop_already_done"
        ts = task.get("done_at")
        message = f"✅ 已是完成状态（{ts}），无需重复标记"
    else:
        now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
        task["done"] = True
        task["done_at"] = now
        message = f"✅ 已标记完成：{task_id}  ({now})"

    save_progress(data, root)
    lane = task.get("lane", "engineering")
    event = append_event(task_id, lane, action_type, result, root)

    total = len(tasks)
    done_count = sum(1 for v in tasks.values() if v.get("done"))

    return {
        "ok": True,
        "task_id": task_id,
        "done": task.get("done", False),
        "done_at": task.get("done_at"),
        "action_type": action_type,
        "result": result,
        "message": message,
        "event_id": event["action_id"],
        "progress": {"done": done_count, "total": total},
        "tasks": data["tasks"],
        "lanes": data["lanes"],
    }


def format_task_list(root: Path | None = None) -> str:
    data = load_progress(root)
    lanes = data["lanes"]
    tasks = data["tasks"]
    by_lane: dict[str, list[tuple[str, dict[str, Any]]]] = {}
    for tid, info in tasks.items():
        lane = info.get("lane", "engineering")
        by_lane.setdefault(lane, []).append((tid, info))

    total_done = sum(1 for v in tasks.values() if v.get("done"))
    lines = [f"📊 总进度：{total_done}/{len(tasks)}\n"]
    ordered = list(lanes.keys()) + [k for k in by_lane if k not in lanes]
    for lane_key in ordered:
        items = by_lane.get(lane_key, [])
        if not items:
            continue
        title = lanes.get(lane_key, {}).get("title", lane_key)
        done_n = sum(1 for _, info in items if info.get("done"))
        lines.append(f"─── {title}（{lane_key}）  {done_n}/{len(items)} ───")
        for tid, info in items:
            if info.get("done"):
                lines.append(f"  ✅ {tid}  ({info.get('done_at')})")
            else:
                lines.append(f"  ⬜ {tid}")
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Progress store CLI (shared with mark_done.sh and learn_server).")
    parser.add_argument("command", choices=["mark", "undo", "list", "json"])
    parser.add_argument("task_id", nargs="?", help="Task id for mark/undo")
    args = parser.parse_args()

    if args.command == "list":
        print(format_task_list())
        return 0

    if args.command == "json":
        print(json.dumps(load_progress(), ensure_ascii=False, indent=2))
        return 0

    if not args.task_id:
        print("task_id required for mark/undo", file=sys.stderr)
        return 1

    try:
        result = set_task_done(args.task_id, undo=args.command == "undo")
    except KeyError as exc:
        data = load_progress()
        known = ", ".join(data.get("tasks", {}).keys())
        print(f"❌ 未知任务 ID：{args.task_id}")
        print(f"   已知 ID：{known}")
        return 1

    print(result["message"])
    print(f"📊 总进度：{result['progress']['done']}/{result['progress']['total']}")
    print(f"📝 已记录事件：{result['event_id']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
