#!/usr/bin/env python3
"""Register progress tasks + UI weeks for scaffold rounds (PW-4)."""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "scripts"))

from round_status import scan_rounds, tier_label  # noqa: E402
from skeleton_progress import build_round_package, register_rounds  # noqa: E402


def sync_progress_rounds_json(start: int = 5, end: int = 21) -> None:
    path = REPO / "progress_rounds.json"
    js_path = REPO / "progress_rounds.js"
    payload = json.loads(path.read_text(encoding="utf-8"))
    by_id = {r["id"]: r for r in payload.get("rounds", [])}

    for n in range(start, end + 1):
        round_dir = REPO / "rounds" / f"round_{n:02d}"
        if not round_dir.is_dir():
            continue
        _, weeks, meta = build_round_package(REPO, n)
        meta["tier"] = tier_label(
            next(s for s in scan_rounds(REPO) if s.number == n)
        )
        entry = by_id.get(meta["id"], {})
        entry.update(meta)
        entry["weeks"] = weeks
        by_id[meta["id"]] = entry

    # Re-merge with scan for rounds 00-04 etc.
    statuses = scan_rounds(REPO)
    merged: list[dict] = []
    for st in statuses:
        if st.round_id in by_id and by_id[st.round_id].get("weeks"):
            entry = dict(by_id[st.round_id])
        elif st.round_id in by_id:
            entry = dict(by_id[st.round_id])
        else:
            continue
        entry["tier"] = tier_label(st)
        entry["progress_linked"] = st.progress_linked or bool(entry.get("weeks"))
        entry["scaffold_only"] = not entry["progress_linked"]
        merged.append(entry)

    payload["rounds"] = merged
    body = json.dumps(payload, ensure_ascii=False, indent=2)
    path.write_text(body + "\n", encoding="utf-8")
    js_path.write_text(
        "// Auto-generated by scripts/sync_skeleton_progress.py\n"
        f"window.PROGRESS_ROUNDS = {body};\n",
        encoding="utf-8",
    )


def main() -> int:
    start = int(sys.argv[1]) if len(sys.argv) > 1 else 5
    end = int(sys.argv[2]) if len(sys.argv) > 2 else 21

    stats = register_rounds(REPO, start=start, end=end, only_missing=True)
    sync_progress_rounds_json(start=start, end=end)

    feedback_script = REPO / "scripts" / "generate_task_feedback.py"
    if feedback_script.is_file():
        subprocess.run([sys.executable, str(feedback_script)], cwd=REPO, check=False)

    print(
        f"sync_skeleton_progress: added {stats['tasks_added']} tasks, "
        f"total {stats['total_tasks']} (rounds {start:02d}-{end:02d})"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
