#!/usr/bin/env python3
"""Round 18 · Final: generate a numeric data analysis project package."""

from __future__ import annotations

import ast
import csv
import json
import shutil
import statistics
import subprocess
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[3]
LAB = Path.home() / "cli-lab" / "round18" / "final_auto" / "numeric_data_lab"

README = """# Round 18 numeric data lab

Generated by the Web UI exercise. It gives you a compact NumPy/pandas-style analysis project without installing dependencies during the automated check.

Files:

- `data/raw_events.csv`: small raw dataset with clean and dirty rows.
- `analysis.py`: pandas/NumPy-style pipeline for read, clean, analyze, export.
- `stdlib_check.py`: dependency-free preview used by the Web UI exercise.
- `analysis_contract.json`: required steps, fields, and outputs.
- `round18_final_summary.json`: static verification report.
"""

ANALYSIS = '''"""Round 18 final analysis package."""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pandas as pd


RAW_PATH = Path("data/raw_events.csv")
OUT_DIR = Path("output")


def load_events(path: Path = RAW_PATH) -> pd.DataFrame:
    df = pd.read_csv(path)
    print("loaded:", df.shape)
    print("missing:")
    print(df.isna().sum())
    return df


def clean_events(df: pd.DataFrame) -> pd.DataFrame:
    clean = df.dropna(subset=["label", "score", "length"]).copy()
    clean = clean[(clean["score"] >= 0) & (clean["score"] <= 1)]
    clean["quality_band"] = pd.cut(clean["score"], bins=[0, 0.5, 0.8, 1.0], labels=["low", "mid", "high"])
    return clean


def summarize(clean: pd.DataFrame) -> dict:
    score_values = clean["score"].to_numpy()
    return {
        "rows": int(len(clean)),
        "label_counts": clean["label"].value_counts().to_dict(),
        "source_score_mean": clean.groupby("source")["score"].mean().round(3).to_dict(),
        "score_percentiles": {
            "p25": round(float(np.percentile(score_values, 25)), 3),
            "p50": round(float(np.percentile(score_values, 50)), 3),
            "p75": round(float(np.percentile(score_values, 75)), 3),
        },
    }


def main() -> None:
    OUT_DIR.mkdir(exist_ok=True)
    raw = load_events()
    clean = clean_events(raw)
    summary = summarize(clean)
    clean.to_csv(OUT_DIR / "clean_events.csv", index=False)
    (OUT_DIR / "analysis_summary.json").write_text(json.dumps(summary, ensure_ascii=False, indent=2), encoding="utf-8")
    print(summary)


if __name__ == "__main__":
    main()
'''

STDLIB_CHECK = '''#!/usr/bin/env python3
"""Dependency-free final preview for the generated analysis package."""

from __future__ import annotations

import csv
import json
import statistics
from pathlib import Path


base = Path(__file__).resolve().parent
with (base / "data" / "raw_events.csv").open("r", encoding="utf-8", newline="") as f:
    rows = list(csv.DictReader(f))

clean = []
for row in rows:
    if not row["label"] or not row["score"] or not row["length"]:
        continue
    score = float(row["score"])
    if 0 <= score <= 1:
        row["score"] = score
        row["length"] = int(row["length"])
        clean.append(row)

label_counts = {}
scores_by_source = {}
for row in clean:
    label_counts[row["label"]] = label_counts.get(row["label"], 0) + 1
    scores_by_source.setdefault(row["source"], []).append(row["score"])

source_score_mean = {
    source: round(statistics.mean(scores), 3)
    for source, scores in sorted(scores_by_source.items())
}
scores = sorted(row["score"] for row in clean)
summary = {
    "raw_rows": len(rows),
    "rows": len(clean),
    "label_counts": label_counts,
    "source_score_mean": source_score_mean,
    "score_min": min(scores),
    "score_max": max(scores),
}
(base / "stdlib_summary.json").write_text(json.dumps(summary, ensure_ascii=False, indent=2) + "\\n", encoding="utf-8")
print(json.dumps(summary, ensure_ascii=False, sort_keys=True))
'''

CONTRACT = {
    "project": "round18_numeric_data_lab",
    "inputs": ["data/raw_events.csv"],
    "required_columns": ["id", "label", "score", "length", "source"],
    "steps": ["load_events", "clean_events", "summarize", "export"],
    "outputs": ["output/clean_events.csv", "output/analysis_summary.json"],
    "concepts": ["ndarray shape", "vectorization", "DataFrame", "filter", "groupby", "missing values"],
}

RAW_ROWS = [
    {"id": 1, "label": "ok", "score": "0.92", "length": "210", "source": "web"},
    {"id": 2, "label": "bad", "score": "0.22", "length": "64", "source": "api"},
    {"id": 3, "label": "good", "score": "0.86", "length": "320", "source": "mobile"},
    {"id": 4, "label": "blur", "score": "", "length": "88", "source": "web"},
    {"id": 5, "label": "ok", "score": "1.12", "length": "130", "source": "api"},
    {"id": 6, "label": "good", "score": "0.97", "length": "190", "source": "web"},
    {"id": 7, "label": "blur", "score": "0.49", "length": "255", "source": "mobile"},
    {"id": 8, "label": "ok", "score": "0.77", "length": "151", "source": "api"},
]

FINAL_CHECK = '''#!/usr/bin/env python3
"""Static final checks for Round 18 numeric data lab."""

from __future__ import annotations

import ast
import csv
import json
import subprocess
import sys
from pathlib import Path


base = Path(__file__).resolve().parent
analysis = (base / "analysis.py").read_text(encoding="utf-8")
ast.parse(analysis)
contract = json.loads((base / "analysis_contract.json").read_text(encoding="utf-8"))
with (base / "data" / "raw_events.csv").open("r", encoding="utf-8", newline="") as f:
    rows = list(csv.DictReader(f))

proc = subprocess.run([sys.executable, "stdlib_check.py"], cwd=base, capture_output=True, text=True, check=False)
summary = {}
if proc.returncode == 0:
    summary = json.loads((base / "stdlib_summary.json").read_text(encoding="utf-8"))

checks = {
    "files_exist": all((base / path).exists() for path in ("README.md", "analysis.py", "analysis_contract.json", "stdlib_check.py", "data/raw_events.csv")),
    "imports": "import numpy as np" in analysis and "import pandas as pd" in analysis,
    "pipeline_functions": all(name in analysis for name in contract["steps"][:-1]),
    "cleaning": ".dropna(" in analysis and 'clean["score"] >= 0' in analysis and 'clean["score"] <= 1' in analysis,
    "dataframe_ops": all(text in analysis for text in ("pd.read_csv", ".to_numpy()", ".groupby(", ".value_counts()", "pd.cut")),
    "exports": "clean_events.csv" in analysis and "analysis_summary.json" in analysis,
    "raw_data": len(rows) == 8 and set(rows[0]) == set(contract["required_columns"]),
    "stdlib_preview": proc.returncode == 0 and summary.get("rows") == 6,
    "concepts": len(contract.get("concepts", [])) >= 6,
}
report = {"ok": all(checks.values()), "checks": checks, "summary": summary, "stderr": proc.stderr.strip()}
(base / "round18_final_summary.json").write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\\n", encoding="utf-8")
print(json.dumps(report, ensure_ascii=False, sort_keys=True))
raise SystemExit(0 if report["ok"] else 1)
'''


def mark(task_id: str) -> None:
    subprocess.run(["bash", str(REPO_ROOT / "mark_done.sh"), task_id], cwd=REPO_ROOT, check=True)


def reset_lab() -> None:
    if LAB.exists():
        shutil.rmtree(LAB)
    (LAB / "data").mkdir(parents=True)


def write_csv(path: Path, rows: list[dict[str, object]]) -> None:
    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=["id", "label", "score", "length", "source"])
        writer.writeheader()
        writer.writerows(rows)


def main() -> None:
    reset_lab()
    (LAB / "README.md").write_text(README, encoding="utf-8")
    (LAB / "analysis.py").write_text(ANALYSIS, encoding="utf-8")
    (LAB / "stdlib_check.py").write_text(STDLIB_CHECK, encoding="utf-8")
    (LAB / "analysis_contract.json").write_text(json.dumps(CONTRACT, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    write_csv(LAB / "data" / "raw_events.csv", RAW_ROWS)
    check = LAB / "final_static_check.py"
    check.write_text(FINAL_CHECK, encoding="utf-8")
    check.chmod(0o755)
    proc = subprocess.run(["python3", str(check)], cwd=LAB, capture_output=True, text=True, check=False)
    if proc.returncode != 0:
        raise RuntimeError(proc.stderr or proc.stdout)
    print("Round 18 综合练习：数值计算与数据分析项目包")
    print("sandbox:", LAB)
    print("contract:", LAB / "analysis_contract.json")
    print("summary:", LAB / "round18_final_summary.json")
    mark("r18-fin-comp")


if __name__ == "__main__":
    main()
