#!/usr/bin/env python3
"""Round 20 · Final: generate a PyTorch intro project package."""

from __future__ import annotations

import ast
import csv
import json
import shutil
import subprocess
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[3]
LAB = Path.home() / "cli-lab" / "round20" / "final_auto" / "pytorch_intro_lab"

README = """# Round 20 PyTorch intro lab

Generated by the Web UI final exercise.

Files:

- `data/toy_points.csv`: small tabular dataset.
- `dataset.py`: Dataset and DataLoader entry point.
- `model.py`: minimal `nn.Module`.
- `train.py`: training loop with loss, backward, optimizer step, and evaluation.
- `checkpoint.py`: save/load state_dict and manifest.
- `torch_workflow_contract.json`: required concepts and outputs.
- `stdlib_smoke.py`: dependency-free smoke check used by Web UI.
- `final_static_check.py`: AST and contract verification.

The generated PyTorch files are real code shapes. They require PyTorch only if you choose to run them outside the Web UI smoke checks.
"""

DATASET = '''"""Dataset and DataLoader shape for Round 20 final project."""

from __future__ import annotations

import csv
from pathlib import Path

import torch
from torch.utils.data import Dataset, DataLoader


class ToyPointDataset(Dataset):
    def __init__(self, path: Path) -> None:
        with path.open("r", encoding="utf-8", newline="") as f:
            rows = list(csv.DictReader(f))
        self.X = torch.tensor([[float(row["x1"]), float(row["x2"])] for row in rows], dtype=torch.float32)
        self.y = torch.tensor([int(row["label"]) for row in rows], dtype=torch.long)

    def __len__(self) -> int:
        return len(self.X)

    def __getitem__(self, index: int):
        return self.X[index], self.y[index]


def build_loader(path: Path, batch_size: int = 4, shuffle: bool = True) -> DataLoader:
    return DataLoader(ToyPointDataset(path), batch_size=batch_size, shuffle=shuffle)
'''

MODEL = '''"""Minimal nn.Module for Round 20 final project."""

import torch
from torch import nn


class PointClassifier(nn.Module):
    def __init__(self, input_size: int = 2, hidden_size: int = 8, num_classes: int = 2) -> None:
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(input_size, hidden_size),
            nn.ReLU(),
            nn.Linear(hidden_size, num_classes),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.net(x)
'''

TRAIN = '''"""Training and evaluation loop for Round 20 final project."""

from __future__ import annotations

import json
from pathlib import Path

import torch
from torch import nn

from checkpoint import save_checkpoint
from dataset import build_loader
from model import PointClassifier


DATA_PATH = Path("data/toy_points.csv")
REPORT_DIR = Path("reports")


def train_one_epoch(model: nn.Module, loader, loss_fn: nn.Module, optimizer: torch.optim.Optimizer) -> float:
    model.train()
    total = 0.0
    for X_batch, y_batch in loader:
        pred = model(X_batch)
        loss = loss_fn(pred, y_batch)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        total += float(loss.item())
    return total / len(loader)


def evaluate(model: nn.Module, loader, loss_fn: nn.Module) -> dict:
    model.eval()
    total = 0.0
    correct = 0
    with torch.no_grad():
        for X_batch, y_batch in loader:
            pred = model(X_batch)
            total += float(loss_fn(pred, y_batch).item())
            correct += int((pred.argmax(dim=1) == y_batch).sum().item())
    return {"loss": round(total / len(loader), 4), "accuracy": round(correct / len(loader.dataset), 4)}


def run_training(epochs: int = 3) -> dict:
    loader = build_loader(DATA_PATH, batch_size=4, shuffle=True)
    model = PointClassifier()
    loss_fn = nn.CrossEntropyLoss()
    optimizer = torch.optim.SGD(model.parameters(), lr=0.1)
    history = []
    for epoch in range(epochs):
        train_loss = train_one_epoch(model, loader, loss_fn, optimizer)
        metrics = evaluate(model, loader, loss_fn)
        history.append({"epoch": epoch, "train_loss": round(train_loss, 4), "metrics": metrics})
    REPORT_DIR.mkdir(exist_ok=True)
    result = {"epochs": epochs, "history": history}
    (REPORT_DIR / "training_summary.json").write_text(json.dumps(result, ensure_ascii=False, indent=2), encoding="utf-8")
    save_checkpoint(model, Path("checkpoints/point_classifier.pt"), {"model": "PointClassifier", "input_shape": ["batch", 2]})
    return result


if __name__ == "__main__":
    print(json.dumps(run_training(), ensure_ascii=False, indent=2))
'''

CHECKPOINT = '''"""Checkpoint helpers for Round 20 final project."""

from __future__ import annotations

import json
from pathlib import Path

import torch
from torch import nn

from model import PointClassifier


def save_checkpoint(model: nn.Module, path: Path, metadata: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    torch.save(model.state_dict(), path)
    path.with_suffix(".manifest.json").write_text(json.dumps(metadata, ensure_ascii=False, indent=2), encoding="utf-8")


def load_checkpoint(path: Path) -> nn.Module:
    model = PointClassifier()
    model.load_state_dict(torch.load(path, map_location="cpu"))
    model.eval()
    return model
'''

STDLIB_SMOKE = '''#!/usr/bin/env python3
"""Dependency-free smoke check for the generated Round 20 project."""

from __future__ import annotations

import csv
import json
from pathlib import Path


base = Path(__file__).resolve().parent
with (base / "data" / "toy_points.csv").open("r", encoding="utf-8", newline="") as f:
    rows = list(csv.DictReader(f))

features = [[float(row["x1"]), float(row["x2"])] for row in rows]
labels = [int(row["label"]) for row in rows]
weight = [0.0, 0.0]
bias = 0.0
lr = 0.1
history = []
for epoch in range(6):
    scores = [weight[0] * row[0] + weight[1] * row[1] + bias for row in features]
    errors = [score - label for score, label in zip(scores, labels)]
    loss = sum(error * error for error in errors) * len(errors) ** -1
    grad_w0 = sum(2 * error * row[0] for error, row in zip(errors, features)) * len(rows) ** -1
    grad_w1 = sum(2 * error * row[1] for error, row in zip(errors, features)) * len(rows) ** -1
    grad_b = sum(2 * error for error in errors) * len(rows) ** -1
    weight[0] = weight[0] - lr * grad_w0
    weight[1] = weight[1] - lr * grad_w1
    bias = bias - lr * grad_b
    history.append({"epoch": epoch, "loss": round(loss, 4), "weight": [round(weight[0], 4), round(weight[1], 4)]})

checkpoint_dir = base / "checkpoints"
checkpoint_dir.mkdir(exist_ok=True)
(checkpoint_dir / "stdlib_state.json").write_text(json.dumps({"weight": weight, "bias": bias}, ensure_ascii=False, indent=2) + "\\n", encoding="utf-8")
(checkpoint_dir / "stdlib_manifest.json").write_text(json.dumps({"model": "linear smoke", "rules": ["save state", "load state", "eval"]}, ensure_ascii=False, indent=2) + "\\n", encoding="utf-8")
summary = {
    "rows": len(rows),
    "feature_count": len(features[0]),
    "initial_loss": history[0]["loss"],
    "final_loss": history[-1]["loss"],
    "loss_decreased": history[-1]["loss"] < history[0]["loss"],
    "workflow": ["Dataset", "DataLoader", "nn.Module", "train loop", "eval", "checkpoint"],
    "checkpoint_files": sorted(path.name for path in checkpoint_dir.glob("stdlib_*.json")),
}
(base / "round20_final_summary.json").write_text(json.dumps(summary, ensure_ascii=False, indent=2) + "\\n", encoding="utf-8")
print(json.dumps(summary, ensure_ascii=False, sort_keys=True))
'''

CONTRACT = {
    "project": "round20_pytorch_intro_lab",
    "inputs": ["data/toy_points.csv"],
    "required_files": ["dataset.py", "model.py", "train.py", "checkpoint.py"],
    "concepts": ["Tensor", "Dataset", "DataLoader", "nn.Module", "loss", "optimizer", "backward", "eval", "no_grad", "state_dict"],
    "outputs": ["reports/training_summary.json", "checkpoints/point_classifier.pt", "round20_final_summary.json"],
}

DATA_ROWS = [
    {"id": 1, "x1": "0.1", "x2": "1.0", "label": "0"},
    {"id": 2, "x1": "0.2", "x2": "1.2", "label": "0"},
    {"id": 3, "x1": "0.3", "x2": "1.4", "label": "0"},
    {"id": 4, "x1": "0.4", "x2": "1.6", "label": "0"},
    {"id": 5, "x1": "1.4", "x2": "0.4", "label": "1"},
    {"id": 6, "x1": "1.6", "x2": "0.3", "label": "1"},
    {"id": 7, "x1": "1.8", "x2": "0.2", "label": "1"},
    {"id": 8, "x1": "2.0", "x2": "0.1", "label": "1"},
]

FINAL_CHECK = '''#!/usr/bin/env python3
"""Final static checks for the Round 20 PyTorch intro project."""

from __future__ import annotations

import ast
import csv
import json
import subprocess
import sys
from pathlib import Path


base = Path(__file__).resolve().parent
sources = {
    name: (base / name).read_text(encoding="utf-8")
    for name in ("dataset.py", "model.py", "train.py", "checkpoint.py")
}
for source in sources.values():
    ast.parse(source)

with (base / "data" / "toy_points.csv").open("r", encoding="utf-8", newline="") as f:
    rows = list(csv.DictReader(f))

proc = subprocess.run([sys.executable, "stdlib_smoke.py"], cwd=base, capture_output=True, text=True, check=False)
summary = {}
if proc.returncode == 0:
    summary = json.loads((base / "round20_final_summary.json").read_text(encoding="utf-8"))

contract = json.loads((base / "torch_workflow_contract.json").read_text(encoding="utf-8"))
checks = {
    "dataset_loader": all(text in sources["dataset.py"] for text in ("Dataset", "DataLoader", "__len__", "__getitem__", "torch.tensor")),
    "model_module": all(text in sources["model.py"] for text in ("nn.Module", "nn.Sequential", "nn.Linear", "def forward")),
    "training_loop": all(text in sources["train.py"] for text in ("model.train()", "optimizer.zero_grad()", "loss.backward()", "optimizer.step()", "model.eval()", "torch.no_grad()")),
    "checkpoint": all(text in sources["checkpoint.py"] for text in ("state_dict", "torch.save", "torch.load", "load_state_dict", "model.eval()")),
    "toy_data": len(rows) == 8 and set(rows[0]) == {"id", "x1", "x2", "label"},
    "stdlib_smoke": proc.returncode == 0 and summary.get("loss_decreased") is True and len(summary.get("checkpoint_files", [])) == 2,
    "contract": len(contract.get("concepts", [])) >= 10,
}
report = {"ok": all(checks.values()), "checks": checks, "summary": summary, "stderr": proc.stderr.strip()}
(base / "final_static_check_report.json").write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\\n", encoding="utf-8")
print(json.dumps(report, ensure_ascii=False, sort_keys=True))
raise SystemExit(0 if report["ok"] else 1)
'''


def mark(task_id: str) -> None:
    subprocess.run(["bash", str(REPO_ROOT / "mark_done.sh"), task_id], cwd=REPO_ROOT, check=True)


def reset_lab() -> None:
    if LAB.exists():
        shutil.rmtree(LAB)
    (LAB / "data").mkdir(parents=True)


def write_data(path: Path) -> None:
    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=["id", "x1", "x2", "label"])
        writer.writeheader()
        writer.writerows(DATA_ROWS)


def main() -> None:
    reset_lab()
    (LAB / "README.md").write_text(README, encoding="utf-8")
    (LAB / "dataset.py").write_text(DATASET, encoding="utf-8")
    (LAB / "model.py").write_text(MODEL, encoding="utf-8")
    (LAB / "train.py").write_text(TRAIN, encoding="utf-8")
    (LAB / "checkpoint.py").write_text(CHECKPOINT, encoding="utf-8")
    write_data(LAB / "data" / "toy_points.csv")
    (LAB / "torch_workflow_contract.json").write_text(json.dumps(CONTRACT, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    (LAB / "stdlib_smoke.py").write_text(STDLIB_SMOKE, encoding="utf-8")
    check = LAB / "final_static_check.py"
    check.write_text(FINAL_CHECK, encoding="utf-8")
    check.chmod(0o755)
    proc = subprocess.run(["python3", str(check)], cwd=LAB, capture_output=True, text=True, check=False)
    if proc.returncode != 0:
        raise RuntimeError(proc.stderr or proc.stdout)
    print("Round 20 PyTorch 入门最终项目包")
    print("sandbox:", LAB)
    print("project:", LAB / "README.md")
    print("report:", LAB / "final_static_check_report.json")
    mark("r20-fin-comp")


if __name__ == "__main__":
    main()
